/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Use Bonus Code": "使用奖励代码",
    "Your world ended, and they only live on through you. Think about what they would\n    have wanted for you, and on how much you miss them, and let it drive you forward. This is an internal story as much\n    as it is an external one.": "你的世界结束了，他们只能通过你活下去。想想他们会对你有什么期望，想想你有多想念他们，让思念驱动你前进。这是一个内部和外部的故事。",
    "You Need A Break": "你需要休息一下",
    "Worry": "担心",
    "/complete)": "/完成)",
    "/lvl": "/等级",
    "/s)": "/秒)",
    "/s": "/秒",
    "Confirm": "确认",
    "Control": "控制",
    "Controls to Move Around": "移动控制",
    "Conversations": "对话",
    "cost:": "成本:",
    "Data": "数据",
    "Attributes": "属性",
    "Deep Investments": "深度投资",
    "Attributes >>": "属性 >>",
    "Aura Control": "光环控制",
    "Aura Healing": "光环愈合",
    "Auto save every 20 seconds and on pause, but if you want a button to click:": "每隔20秒自动保存并暂停，但如果你想点击按钮：",
    "Awaken Your Grimoire": "唤醒你的魔法书",
    "Background": "背景色",
    "Basic Training With John": "约翰的基础训练",
    "Bind The Pages": "绑定页面",
    "Body Awareness": "身体意识",
    "Bonus Time:": "加成时间:",
    "Bonus Speed:": "加成速度:",
    "bonus mult": "加成乘数",
    "Bridge Of Bone": "骨桥",
    "Browse Stores": "浏览商店",
    "Burn Flesh Pits": "烧肉坑",
    "Buy": "购买",
    "Buy Coffee": "购买咖啡",
    "Buy Social Access": "购买社交访问",
    "Buy Shop Items": "购买商店物品",
    "Buy Good Food": "购买美食",
    "Buy Street Food": "购买路边食物",
    "Buy Basic Clothes": "购买基础衣服",
    "Buy Matching Clothes": "购买搭配衣服",
    "Buy Stylish Clothes": "购买时尚衣服",
    "Buy Travelers Clothes": "购买旅行者衣服",
    "Buy Basic Supplies": "购买基础物资",
    "Buy Bonus Time:": "购买加成时间:",
    "Changing Colors": "更改颜色",
    "Change": "更改",
    "Charges": "充能",
    "Charm": "魅力",
    "Chat With Hermit": "与隐士对话",
    "Chat With Merchants": "与商人对话",
    "Clock:": "时钟:",
    "CLOSED BETA": "封闭测试",
    "Command": "Command",
    "View Amulet Upgrades!": "查看护身符升级！",
    "Vision": "视野",
    "WAIT": "等待",
    "Walk Aware": "行走意识",
    "Ward": "结界",
    "Ward Magic": "结界魔法",
    "Unlocks 5 new actions.": "解锁5个新动作",
    "Use the Amulet!": "使用护身符！",
    "Valor": "英勇",
    "Wizardry": "巫术",
    "Work in Progress. The shop will be completed for full release with the following plans. \n        I will keep the game ad-free and AI-art free, and the demo will be open-source on my github.": "工作进行中。商店将完成全面发布与以下计划。我将保持游戏不含广告和ai图像，demo将在我的github上开源。",
    "You can fully delete the numbers in sliders now": "您现在可以完全删除滑块中的数字",
    "You pay respect to the shrine, \n        and feel your amulet resonate with feelings around this shrine.": "你对神殿表示敬意，并感到你的护身符与神殿周围的情感产生共鸣。",
    "You will gain progress using Total Momentum, Hear About The Lich's level, and Spell Power!": "你将通过使用总动量，听说巫妖的等级和法术力量获得进步！",
    "You'll help me, for real? Wow, I didn't know you were cool like that.": "你会帮我，真的吗？哇，我不知道你这么酷。",
    "You'll help? Oh, you": "你会帮忙吗？哦，你",
    "Your motivation to overclock spills over throughout your mind. Your general drive expands, and you put this to use in making money. At first it's whatever odd jobs you can find, with later getting employed, Making Money is the gateway to improving your situation.": "你想要超频的动机充斥着你的大脑。你的整体动力得到了扩展，你把它用于赚钱。一开始是你能找到的任何奇怪的工作，随着之后的工作，赚钱是改善你的状况的途径。",
    "Mana": "法力",
    "mana": "法力",
    "Mana Basics": "法力基础",
    "Mana Experiments": "法力实验",
    "Mana Instinct": "法力本能",
    "Mana Observations": "法力观察",
    "Mana Shaping": "法力塑造",
    "Mana Transfer": "法力转移",
    "Mana Visualizations": "法力可视化",
    "Mana, added to this action.": "法力，添加到此动作。",
    "Mass Heal": "群体治疗",
    "MAX CHARGES": "充能上限",
    "Max Level": "最大等级",
    "MAX LEVEL": "最大等级",
    "Meditate": "冥想",
    "Meet Grumpy Hermit": "Meet Grumpy Hermit",
    "Meet People": "结识新朋友",
    "Menu": "菜单",
    "Might": "实力",
    "Modified text of on-level attributes": "修改了等级属性的文本",
    "Messenger": "信使",
    "On Complete:": "完成:",
    "Offline >>": "离线 >>",
    "Offline time constantly saves instead of only when the page unloads": "离线时间会不断地节省下来，而不仅仅是在页面卸载时",
    "NOTICE - Market Ads": "公告 - 市场广告",
    "NOTICE - A hidden notice": "公告 - 一个隐藏的通知",
    "NOTICE - Report for Training": "公告 - 训练报告",
    "Notice The Strain": "注意张力",
    "Number Notation": "数字符号",
    "Odd Jobs Laborer": "临时工",
    "Off": "关闭",
    "On": "开启",
    "Detect Magic": "侦测魔法",
    "Destroy Western Monolith": "摧毁西方巨石",
    "Destroy Southern Monolith": "摧毁南方巨石",
    "Destroy Northern Monolith": "摧毁北方巨石",
    "Destroy Eastern Monolith": "摧毁东方巨石",
    "Destroy Flesh Growths": "摧毁肉体生长",
    "Deception": "欺骗",
    "Delta Unlock Time:": "德尔塔解锁时间:",
    "Cycle": "周期",
    "Current Job:": "当前工作:",
    "Current Unlock Time:": "当前解锁时间:",
    "...Ask Scott More Questions": "...斯科特更多问题",
    "...Buy Nicer Stuff": "...买更好的东西",
    "legacy": "遗物",
    "Legacy": "遗物",
    "Level": "等级",
    "Let Go Of Guilt": "放下内疚",
    "Logarithmic": "对数",
    "Listen To The Mana": "聆听法力",
    "Listen To Woes": "聆听悲伤",
    "Logistics": "物流",
    "Magic": "魔法",
    "Research": "研究",
    "Make Money": "赚钱",
    "Making Money": "赚钱",
    "Momentum": "动量",
    "momentum": "动量",
    "Meet Village Leader Scott": "会见村长斯科特",
    "Money": "金钱",
    "Move Earth": "动天地",
    "Move With Purpose": "有目的的行动",
    "Needs": "需要",
    "Navigation": "导航",
    "Observation": "观察",
    "On Level up:": "当升级:",
    "Welcome to Kill the Lich! Click Here for Info!": "欢迎来到《杀死巫妖》！点击这里获取信息！",
    "Exp and Leveling": "经验与等级",
    "Watch Birds": "观鸟",
    "progress\n                (+": "进度\n                (+",
    "Processing": "处理中",
    "Process Emotions": "处理情绪",
    "Previous Unlock Time:": "前一次解锁时间:",
    "Previously Closed Tips": "以前关闭的提示",
    "Previous Tips": "之前的提示",
    "Purify Poison": "净化毒药",
    "Raising Max Levels": "提高最大等级",
    "Put your save here to import (import a clear save to hard reset):": "把你的存档放在这里导入（导入一个清晰的存档来硬重置）：",
    "|| Pause": "|| 暂停",
    "Spend Money": "花钱",
    "Start Again": "重新开始",
    "Starting the Game": "开始游戏",
    "Stat Modifiers to Efficiency:": "效率的属性修饰：",
    "Stats": "属性",
    "Stop Darkness Ritual": "停止黑暗仪式",
    "Stop_Sign Gaming": "Stop_Sign 游戏",
    "Story": "故事",
    "Story Teller": "说书人",
    "Suffix": "后缀",
    "Toast Title": "祝酒称号",
    "Total Momentum,": "总动量，",
    "Total Momentum:": "总动量:",
    "exp\n                (+": "经验值\n                (+",
    "Energy": "能量",
    "Endurance": "耐力",
    "Enter Bonus Code:": "输入奖励代码：",
    "Etch The Circle": "蚀刻圆圈",
    "Downstream": "下游",
    "Browse Local Market": "浏览本地市场",
    "Browse Personal Collection": "浏览个人收藏",
    "Browse Backrooms": "浏览密室",
    "Breathe Through It": "透过它呼吸",
    "Overclock": "超频",
    "Overdrive": "超速",
    "Own The Weight": "拥有重量",
    "per level": "每级",
    "Physique": "体格",
    "Pleasant Forest": "宜人森林",
    "Pool Mana": "池法力",
    "Prepare Spells": "准备法术",
    "Pulse": "脉冲",
    "Purge Unholy Relics": "清除不洁圣物",
    "Read Books": "读书",
    "Reflect": "反射",
    "Recognition": "认可",
    "sent from": "发送来自",
    "Shop": "商店",
    "Show +/-/Δ Values": "显示 +/-/Δ 值",
    "Slide The Coin": "滑动硬币",
    "Socialization": "社会化",
    "Sort By Subject": "按主题分类",
    "Spell": "法术",
    "Spell Power:": "法术力量:",
    "Spot A Path": "找到一条路",
    "Stand Straighter": "站得更直",
    "Tell A Joke": "讲个笑话",
    "Buy Market Items": "购买市场物品",
    "Build Fortune": "创造财富",
    "Catalog New Books": "编目新书",
    "Catch A Scent": "捕捉气味",
    "Changing your overclock target will set you on a new path to get as much Ancient Coins and Legacy as you can.": "改变你的超频目标将使你走上一条新的道路，以获得尽可能多的古币和遗物。",
    "Check Notice Board": "检查公告栏",
    "Bonus = 10% per Stat.": "奖励 = 10% 每属性.",
    "Integration": "集成",
    "Inquire About Magic": "询问魔法",
    "Increase": "增加",
    "Influence": "影响",
    "Infuse The Hide": "浸皮",
    "Invest In Roads": "投资道路",
    "Invest In Locals": "投资本地",
    "Introspection": "自省",
    "Spellcraft": "法术制作",
    "Stat Modifiers to Exp:": "经验的属性修饰：",
    "Stillness": "静止",
    "Support Spells": "支持法术",
    "Survive Living Siege Engine": "求生攻城引擎",
    "Enable Bonus Speed": "启用奖励速度",
    "Overboost": "超增压",
    "Overcharge": "过度充能",
    "Tavern Helper": "酒馆助手",
    "Thanks for playing!": "谢谢你的参与！",
    "Take Notes": "做笔记",
    "Swarm Spells": "群体法术",
    "Stats gained each level:": "每级属性增益：",
    "How to Provide Feedback": "如何提供反馈",
    "Hear About The Lich": "听说巫妖的事",
    "Heal Burst": "治愈爆发",
    "Healing Magic": "治愈魔法",
    "Help For Real": "真正的帮助",
    "Help Scott With Chores": "帮斯科特做家务",
    "Here is a message": "这里有一条消息",
    "gold": "金币",
    "Gold": "金币",
    "Gold generation increased by 50%": "金币产量增加50%",
    "gold, added to Spend Money.": "金币，增加到花钱。",
    "Harness Overflow": "利用溢出",
    "Handyman": "杂工",
    "Harvest Ghostly Field": "收获幽灵田",
    "Geyser Fields": "间歇泉田",
    "Gather Rare Plants": "收集稀有植物",
    "Gather Old Books": "收集旧书",
    "Gather River Weeds": "收集河道杂草",
    "Join the War for Life with": "加入生命之战",
    "Kill The Architect": "杀死建筑师",
    "Journal": "日记",
    "Distill Insight": "蒸馏洞察力",
    "Join Coffee Club": "加入咖啡俱乐部",
    "Learn To Listen": "学会倾听",
    "Kill Dopplegangers": "击杀分身",
    "Key To The Backroom": "密室的钥匙",
    "Kill Death Knights": "击杀死亡骑士",
    "Keep 50% (Currently 10%) of your Legacy when you use the Amulet": "当你使用护身符时，保留50%（现在是10%）的遗物",
    "Layer The Echoes": "分层回声",
    "Leave The Open Road": "Leave The Open Road",
    "Learn To Stay Still": "学会保持静止",
    "Leverage": "杠杆作用",
    "Linear": "线性",
    "Momentum was added.": "动量增加了。",
    "Fight": "战斗",
    "fight": "战斗",
    "Fight The Evil Forces": "对抗邪恶势力",
    "Fight The Lich": "对抗巫妖",
    "Fight, added to Fight The Evil Forces.": "战斗，添加对抗邪恶力量。",
    "Find Overlook": "发现远眺",
    "Game Math on Sending": "发送的游戏数学",
    "Finding New Actions": "寻找新动作",
    "Help": "帮助",
    "Hesitation": "犹豫",
    "Hidden Path": "隐藏路径",
    "Honor The Lost": "纪念逝者",
    "Highest level (2x up to):": "最高级别（最高可达2x）：",
    "Guild Receptionist": "公会接待员",
    "Grow Magic Senses": "培养魔法感官",
    "Click/right click and drag to move the game window. WASD works also. Use the mouse scroll wheel or the [+]\n        and [-] to zoom in and out.": "点击/右击并拖动移动游戏窗口。WASD也可以。使用鼠标滚轮或[+]\n和[-]来放大和缩小。",
    "Attention Bonus": "注意力奖励",
    "To send resources between actions faster, you can click the solid blue lines between the actions, which sets the attention bonus. For now, you can set \n        up to 2 at a time, and they give a x2 to the send rate!": "为了更快地在行动之间发送资源，你可以点击行动之间的蓝色实线，这将设置注意力奖励。现在，您可以一次设置\n最多2个，它们会给发送速率一个x2 ！",
    "This is Kill the Lich, an idle/waiting optimization game! These messages will serve as the tutorial, so\n        make sure to click these popups and read them for important information when you can!": "这是杀死巫妖，一个空闲/等待优化游戏！这些消息将作为教程，所以请确保点击这些弹出窗口，并在可以的时候阅读它们以获取重要信息！",
    "You've already started!": "你已经开始了！",
    "Closed messages are still accessible at Menu -> Previous Tips.": "关闭的消息仍然可以在 菜单 -> 先前提示 中访问。",
    "24hr for 2000 SC": "24小时 花费 2000 古币",
    "Absorb Starseed": "吸收星种",
    "Each attribute is a 10% increase to bonus, shown in the Attributes window. You can click an attribute to see which actions use it. There are 3 colors:": "每个属性的加成增加10%，在属性窗口中显示。您可以单击某个属性以查看哪些操作使用它。有3种颜色：",
    "Exp & Conversations gain = (Momentum Taken/1e12)^.5 * Action Power * Efficiency.": "经验和对话增益 =（获得的动量/1e12）^.5 * 行动力量 * 效率。",
    "Efficiency, found in the title, is Expertise Mult * Base Efficiency (x": "效率，可以在标题中找到，是专业乘数 * 基础效率(x",
    "exp required to level": "等级经验要求",
    "Expel Mana": "驱逐法力",
    "Explore The Forest": "探索森林",
    "Explore Difficult Path": "探索困难之路",
    "fear": "恐惧",
    "Fear": "恐惧",
    "Travel On Road": "旅行在路上",
    "Travel Along The River": "沿河旅行",
    "Town Crier": "城镇传令官",
    "bonus": "加成",
    "Awareness": "意识",
    "Curiosity": "好奇心",
    "conversations": "对话",
    "Coordination": "协调",
    "Courage": "勇气",
    "Crack Corrupted Eggs": "有裂纹的鸡蛋",
    "conversations, added to Meet People.": "对话，添加到认识的人。",
    "Adventuring": "冒险",
    "Confidence": "信心",
    "Concentration": "专注",
    "Travel To Outpost": "前往前哨站",
    "Unblemish": "完美无瑕",
    "Travel To Crossroads": "前往十字路口",
    "Action": "动作",
    "Adaptability": "适应性",
    "Ambition": "野心",
    "Remaining:": "剩余:",
    "Remember": "记忆",
    "x2 conversations for 24hr: 200 SC": "x2 对话 持续 24小时: 200 古币",
    "x2 game speed for 24hr: 2000 SC": "x2 游戏速度 持续 24小时: 2000 古币",
    "x2 momentum for 24hr: 200 SC": "x2 动量 持续 24小时: 200 古币",
    "x2 gold for 24hr: 200 SC": "x2 金币 持续 24小时: 200 古币",
    "x2 mana for 24hr: 200 SC": "x2 法力 持续 24小时: 200 古币",
    "x2 legacy for 24hr: 600 SC": "x2 遗物 持续 24小时: 600 古币",
    "Tip #4: Attention Bonus": "提示 #4: 注意力加成",
    "Tip #3: Controls to Move Around": "提示 #3: 移动控制",
    "Tip #2: Starting the Game": "提示 #2: 开始游戏",
    "Tip #1: Welcome to Kill the Lich! Click Here for Info!": "提示 #1: 欢迎来到《杀死巫妖》！点击这里获取信息！",
    "Read The Written": "读写",
    "Read War Journals": "阅读战争杂志",
    "Rebuked by the Hermit": "被隐士斥责",
    "Recent 100 Overclock Amounts": "最近100超频数",
    "Reflex": "反射",
    "Recover Spells": "恢复法术",
    "Reinforce Armor": "强化护甲",
    "Remember has an additional on-level effect, check its Info.": "记忆 有一个额外的层效果，检查它的信息。",
    "As you come to terms with what momentum can be for, you know that you need to do what you've \n        been dreading: making connections in the local community. The closer you get, though, the more it reminds you of things you had put aside.": "当你开始接受动量的作用时，你知道你需要做你一直害怕的事情：在当地社区建立联系。然而，你越靠近它，它就越能让你想起你已经搁置的东西。",
    "At this village there are not many things to buy, but there are still the essentials you need. Buying things with the money you've earned gets you confidence, and the things improve your life to gain more energy.": "在这个村子里，没有多少东西可以买，但仍然有你需要的必需品。用你赚来的钱买东西会让你更有信心，这些东西会让你的生活变得更有活力。",
    "As you lay dying, your last thoughts are recorded by the amulet...": "当你奄奄一息的时候，你最后的想法会被护身符记录下来……",
    "Brythal and Magic will be paused and unchangeable while you are at war.": "当你处于战争状态时，布里塔尔和魔法将被暂停并且不可改变。",
    "Generator": "生成器",
    "Gossip Around Coffee": "咖啡八卦",
    "FPS setting will save correclty": "FPS设置将正确保存",
    "fortune": "财富",
    "Fortune": "财富",
    "Forgotten Shrine": "被遗忘的神殿",
    "Gain a rate of +1/hr to a Practice Mult on the flow you have Focused. The mult lasts until the amulet \n                is used, and stacks with the Focus Mult. The Practice Mult will have a max of 2.": "在你专注的过程中获得+1/小时速率的练习乘数。护身符一直持续到护身符\n被使用，并与专注护身符叠加。练习乘数最多有2个。",
    "Feel A Gentle Tug": "感受温柔的牵引",
    "Feel The Resonance": "感受共鸣",
    "Feel Your Mana": "感受你的法力",
    "Fight gain = (Momentum Taken/1e24)^.5 * Spell Power.": "战斗增益 =（获得的动量/1e24）^.5 * 法术力量。",
    "Eat Golden Fruit": "吃金币水果",
    "Earth Magic": "土系魔法",
    "Duelling Spells": "决斗法术",
    "Divination": "占卜",
    "1 hr for 200 SC": "1 小时 花费 200 灵魂币",
    "'s bonus \n            = x": "加成 \n            = x",
    "), capping at": "), 上限在",
    "Total Expertise Mult = x": "总经验乘数 = x",
    "% of": "% 的",
    "[Automation] When an action is at its max level and has no downstream actions with sliders, it \n                automatically set the flow rate leading to it to 0%. This will apply recursively.": "[自动化]当一个动作处于最大等级并且没有滑块的下游动作时，它会自动将导致它的流量设置为0%。这将递归地应用。",
    "[Automation] When unlocking a new action, automatically sets the downstream sliders of the \n            unlocked action to 50%.": "[自动化] 解锁新动作时，自动将\n解锁动作的下行滑块设置为50%。",
    "Stat Modifiers to Progress:": "进度的属性修饰：",
    "Talk To Hermit": "与隐士对话",
    "Thanks for playing! -Stop_Sign": "谢谢你的参与！-Stop_Sign",
    "The board was stuffed with notices. Surely something else is relevant for you.": "公告板上贴满了告示。肯定还有其他与你相关的事。",
    "The foliage on the mountain becomes too thick to move in and find the source of the scent, \n        but you can at least tell Scott that you shared his experience.": "山上的树叶变得太厚了，无法进入并找到气味的来源，但你至少可以告诉斯科特，你和他有同样的经历。",
    "There will be a \"daily bonus\" button for +100 soul coins (and 30m of bonus speed) every 23hr, \n        and it upgrades to +200 in ~30 days.": "将有一个“每日奖励”按钮，每23小时+100个灵魂币（和30分钟奖励速度），并在30天内升级到+200。",
    "Third Highest level (2x up to):": "第三高等级（最多2x）：",
    "This action gains (Momentum)^0.25 * (Conversation)^0.5 / 1e12 Fear \n        for each Overclock complete, which is a gain of": "每完成一次超频，此动作获得（动量）^0.25 *（对话）^ 0.5 / 1e12 恐惧\n，一个增益对于",
    "Tier": "层",
    "Timed Resource Bonuses (repeated use adds to timer):": "定时资源奖励（重复使用增加计时器）：",
    "Tip #12: Raising Max Levels": "提示 #12: 提高最大等级",
    "to ": "到 ",
    "to Action Power per level": "到每级的动作力量",
    "Total bravery sending downstream: ": "往下游发送的总 勇敢 量：",
    "Total fear sending downstream: ": "往下游发送的总 恐惧 量：",
    "Total fight sending downstream: ": "往下游发送的总 战斗 量：",
    "Total fortune sending downstream: ": "往下游发送的总 财富 量：",
    "Total gold sending downstream: ": "往下游发送的总 金币 量：",
    "Total mana sending downstream: ": "往下游发送的总 法力 量：",
    "Total momentum sending downstream: ": "往下游发送的总 动量 量：",
    "Total spark sending downstream: ": "往下游发送的总 火花 量：",
    "Total legacy sending downstream: ": "往下游发送的总 遗物 量：",
    "Total conversations sending downstream: ": "往下游发送的总 对话 量：",
    "total Action Power from level)": "总动作力量从等级)",
    "Geared": "齿轮传动",
    "+2 max levels for Remember.": "+2 记忆等级上限。",
    "+50% permanent conversations (up to 2): 500 SC, 1k SC": "+50% 永久对话 (最多 2): 500 灵魂币, 1k 灵魂币",
    "+50% permanent gold (up to 2): 500 SC, 1k SC": "+50% 金币 (最多 2): 500 灵魂币, 1k 灵魂币",
    "+50% permanent mana (up to 2): 500 SC, 1k SC": "+50% 法力 (最多 2): 500 灵魂币, 1k 灵魂币",
    "+50% permanent momentum (up to 2): 500 SC, 1k SC": "+50% 动量 (最多 2): 500 灵魂币, 1k 灵魂币",
    "Added a button to hide Attributes": "添加一个按钮来隐藏属性",
    "All attributes will reset.": "所有 属性 将被重置。",
    "All Brythal actions will reset.": "所有 布立塔尔动作 将被重置。",
    "All Magic actions will reset except for the unlock cost.": "除解锁费用外，所有魔法动作将重置。",
    "Altered some text descriptions": "修改了一些文字描述",
    "Savvy": "悟性",
    "bravery": "勇敢",
    "Bravery": "勇敢",
    "Ask About Stitching": "询问缝纫",
    "Break Flesh Barricade": "破肉路障",
    "Break Out Of Endless Maze": "打破无尽的迷宫",
    "Chimney Sweep": "烟囱清洁工",
    "Clear Ivy Wall": "清理常春藤墙",
    "Clench The Jaw": "咬紧牙关",
    "Climb The Rocks": "攀爬岩石",
    "Resolve": "决心",
    "Resonance Compass": "共振指南针",
    "Rhythm": "节奏",
    "Rest At Waterfall": "在瀑布休息",
    "Repair Equipment": "修理装备",
    "Report For Labor": "劳工报告",
    "Report For Training": "训练报告",
    "Single Target Healing": "单体治疗",
    ". Wage: $": ". 工资: $",
    "Introductions with Scott as a village leader are nothing to note - he tells me not to make trouble and that he's open to chatting about any problems. He wants to help make the community work well. He seems like a good man. Past the introductions, when I really strike up a conversation with him, he opens up. \n\n\"Did you see any birds on the road?\" the softly smiling man asks me, after we got the pleasantries out of the way. I didn't think to look for the birds, and told him so. \"You should have! There's a particularly golden one I only got a glimpse of!\" He's passionate about this, but I am not. There might still be something worthwhile in finding this \"golden bird\" though.\n\nI ask if I can help out, and he gives me a job! It's just helping him out with some chores, but he pays me for it.\n\nScott is really nice. I wish more people like him existed - my life would have gone differently. The more I chat with him, the more I remember the few soldiers I knew who were similar. It's a good connection, a good memory, and I have precious few of those. \n\nIt also reminds me of how those men died, which starts to be more than I can handle for the moment. I have to start reminding myself that this is somewhere safe, but ultimately I am not quite up to do the task of socialization. I'm glad I ended up here though, and for the peace it has offered me.\n": "斯科特被介绍为村长，这没什么大不了的——他告诉我不要制造麻烦，他愿意就任何问题和我聊天。他想帮助社区更好地运作。他看起来是个好人。介绍过后，当我真正开始和他交谈时，他敞开了心扉。\n\n“你看见路上有鸟吗？”寒暄过后，那个面带微笑的男人问我。我没有想到去找鸟，就这样告诉了他。“你应该这么做！”有一个特别金色的，我只瞥见了一眼！“他对此充满热情，但我没有。不过，找到这只“金鸟”可能还是有价值的。我问他能不能帮忙，他就给了我一份工作！只是帮他做些家务，但他付钱给我。斯科特人真的很好。我希望有更多像他这样的人存在——我的人生将会有所不同。我和他聊得越多，我就越记得我认识的几个和他相似的士兵。这是一种很好的联系，一段美好的回忆，而我拥有的很少。这也让我想起那些人是怎么死的，这让我一时无法承受。我不得不开始提醒自己，这是一个安全的地方，但最终我还不能完成社会化的任务。不过，我很高兴能来到这里，因为这里给了我平静。\n",
    "It is my worst nightmare become reality; the lich has returned. My lost home country, Sovvgor, had only ever delayed the \n        lich with the Emperor's Curse. All I had known, all the horror I had witnessed... was only a delay. Perhaps that situation\n        was engineered by the lich in the background, in order to get around the blockade of the Curse.": "这是我最糟糕的噩梦变成了现实；巫妖回来了。我失去的祖国，索夫戈，只是用皇帝的诅咒推迟了巫妖的降临。我所知道的一切，我所目睹的一切恐怖……只是耽搁了一下。也许那个情况\n是巫妖在幕后策划的，为了绕过诅咒的封锁。",
    "On each action, get 2x exp as long as the action's level is lower than the highest level ever reached. The action's highest level will be recorded on amulet use, and it will be displayed.": "在每个行动中，只要行动的等级低于所达到的最高等级，就可以获得2倍的经验值。该行动的最高等级将记录在护身符的使用上，并将显示出来。",
    "On each action, get 2x exp as long as the action's level is lower than the second highest level ever reached. The action's second highest level will be recorded on amulet use, and it will be displayed.": "在每个行动中，只要行动的等级低于第二高的等级，就可以获得2倍的经验值。这个动作的第二高等级会记录在护身符的使用上，并且会显示出来。",
    "On each action, get 2x exp as long as the action's level is lower than the third highest level ever reached. The action's third highest level will be recorded on amulet use, and it will be displayed.": "在每个行动中，只要该行动的等级低于第三个最高等级，就可以获得2倍的经验值。该动作的第三级将被记录在护身符的使用上，并显示出来。",
    "On level, +1 ": "在等级, +1 ",
    "Open Soul Gate": "打开灵魂之门",
    "help. Well, use the sliders to move resources to actions that haven't been unlocked yet. \n        Other than that, it's just reading the numbers that are visible and figuring out which is the optimal path. I'm sure you can do it.": "的帮助。使用滑块将资源移动到尚未解锁的动作。除此之外，它只是读取可见的数字，并找出哪条是最优路径。我相信你能做到。",
    "Identify Item": "识别物品",
    "Unique Upgrades:": "独特升级:",
    "Unlocks when Gossip Around Coffee is level 5.": "当八卦咖啡达到5级时解锁",
    "Maybe it would better to process some memories first.": "也许最好先处理一些记忆。",
    "Learn to Listen max level is 10 (will apply next amulet use)": "学会倾听最高等级为10（将适用于下一次护身符使用）",
    "Most actions will automatically convert their sending rate to exp, essentially a 100% slider bar you can't turn off.": "大多数动作会自动将其发送率转换为经验值，本质上是一个你无法关闭的100%滑动条。",
    "While off to the side of the path, you, at Scott's suggestion, focus on what you can \n        smell as well. Sometimes there's a certain scent on the breeze, like something sweet, hiding on the mountain.": "当你走到路边时，按照斯科特的建议，把注意力集中在你能闻到的东西上。有时微风中有一种特定的气味，就像某种甜蜜的东西，隐藏在山上。",
    "Invest": "投资",
    "...Check What Scott Mentioned": "…检查斯科特提到的内容",
    "...Create A Better Foundation": "…创造更好的基础",
    "...Discover More Of The World": "…发现更多的世界",
    "...Feel The Echoes Of My Past": "…感受我过去的回声",
    "...Focus Harder": "…更难集中注意力",
    "...Have Better Conversations": "…进行更好的对话",
    "...Know What I Focused On": "…知道我关注的是什么",
    "...Know When To Move On": "…知道什么时候该向前看",
    "...Learned Of Lich Signs": "…了解巫妖的征兆",
    "...Look Closer At The Board": "…仔细观察董事会",
    "...Make More Money": "…赚更多的钱",
    "...Refine My Adaptability": "…提高我的适应能力",
    "...Refine My Ambition": "…完善我的抱负",
    "...Refine My Amplification": "…改进我的放大效果",
    "...Refine My Awareness": "…完善我的意识",
    "...Refine My Charm": "…提升我的魅力",
    "...Refine My Concentration": "…提高我的注意力",
    "...Refine My Confidence": "…提升我的自信",
    "...Refine My Control": "…完善我的控制",
    "...Refine My Coordination": "…完善我的协调能力",
    "...Refine My Courage": "…磨练我的勇气",
    "...Refine My Cunning": "…磨练我的狡猾",
    "...Refine My Curiosity": "…激发我的好奇心",
    "...Refine My Cycle": "…完善我的周期",
    "...Refine My Discernment": "…改善我的洞察力",
    "...Refine My Endurance": "…提高我的耐力",
    "...Refine My Energy": "…改善我的能量",
    "...Refine My Flow": "…完善我的心流",
    "...Refine My Geared": "…完善我的齿轮",
    "...Refine My Influence": "…改善我的影响力",
    "...Refine My Integration": "…完善我的整合",
    "...Refine My Might": "…精炼我的力量",
    "...Refine My Navigation": "…完善导航",
    "...Refine My Observation": "…完善我的观察",
    "...Refine My Pulse": "…改善我的脉搏",
    "...Refine My Recognition": "…提高我的辨识度",
    "...Refine My Savvy": "…提高我的悟性",
    "...Refine My Spark": "…提炼我的火花",
    "...Refine My Vision": "…完善我的视野",
    "...Refine My Wizardry": "…完善我的魔法",
    "...Remember How I Grew": "…记得我是如何成长的吗？",
    "...Remember My Mastery": "…记住我的精通",
    "...Remember What I Did": "…记住我做过的事",
    "...Remember What I Focused On": "…记住我关注了什么",
    "...Start A Little Quicker": "…开始得快一点",
    "...Stop Being So Tense": "…别那么紧张",
    "...Stop Letting Opportunity Wait": "…不要让机会等待",
    "(Increase / Decrease) Ratio:": "（增加/减少）比例：",
    "Added a mesage at unlocking Ghostly Fields saying \"that's all for now\"": "在解锁幽灵领域时增加了一条消息，说“现在就这样了”。",
    "Added version in top right": "右上方新增版本",
    "Adds equal Fear and Bravery to this action and Resolve.": "为这个动作和决心增加相等的恐惧和勇敢。",
    "After you get as many resources as you can, there will only be the option to reset:": "当你获得了尽可能多的资源后，你将只能选择重置：",
    "Amplification": "放大",
    "Ancient Coins available:": "古币可用：",
    "Ancient Coins:": "古币：",
    "Annoy Hermit Into A Quest": "在任务中惹恼隐士",
    "Archmagery": "大魔法术",
    "Bravery, added to Resolve.": "勇敢，加入决心。",
    "Build Personal Library": "建立个人图书馆",
    "Collapse Corpse Tower": "坍塌尸塔",
    "Combat Spells": "战斗法术",
    "Comfort": "安慰",
    "Compliment The Chef": "赞美厨师",
    "Conquer The Gatekeepers": "征服守门人",
    "Conversation generation increased by 50%": "对话生成增加了50%",
    "Cunning": "狡猾",
    "Decrease": "减少",
    "Destroy Siege Engine": "摧毁攻城引擎",
    "Diplomacy": "外交",
    "Discernment": "洞察力",
    "Disclaimer: Game will be balanced without these upgrades.": "免责声明：没有这些升级，游戏将保持平衡。",
    "Discover Burnt Town": "发现被烧毁的小镇",
    "Doom": "厄运",
    "Echo Kindle": "回声Kindle",
    "Echoes": "回声",
    "Exp & Gold gain = (Momentum Taken)^.5 * Action Power * Efficiency * Wages.": "经验和金币增益=（动量）^。5 *行动力量*效率*工资。",
    "Exp & Mana gain = (Legacy)^.5 * Action Power * Efficiency * 1000.": "经验和法力增益=（遗物）^。5 *动作功率*效率* 1000。",
    "Exp & Mana gain = Action Power * Efficiency.": "经验和法力增益=行动能量*效率。",
    "Fear to this action, and also": "对这一行动的恐惧，也",
    "Fireball": "火球",
    "Firebolt": "火弩箭",
    "Fixed a timing bug for mobile (mobile still very clunky)": "修正了手机版的计时错误（手机版仍然很笨拙）",
    "Fixed filtering upgrades": "固定过滤升级",
    "Fixing number validation": "固定号码验证",
    "Flow": "流动",
    "Focus Bars mult (up to x4): 1k SC each": "多个焦点条（最多4个）：每个1k SC",
    "Harvest Ghostly Field now saves properly": "收割幽灵田现在可以正常保存了",
    "He said something about seeing a spot of gold among the trees. \n            The birds, maybe? It might have been worth checking out.": "他说在树林里看到了一块金子。\n也许是鸟？也许值得一看。",
    "If a charge is available, the next Overclock will give x10 momentum.": "如果充电是可用的，下一个超频将给予x10的动量。",
    "If an Overboost charge is available, the next Overcharge will be x10 effect.": "如果有过充能，下一次过充能效果为10倍。",
    "IF ONLY I COULD JUST...": "要是我能……",
    "Ignite The Spark": "点燃火花",
    "Illuminate": "照亮",
    "In addition, +2 max levels for Remember when this action levels.": "另外，+2最高等级为记住当这个行动等级。",
    "Increase the max level of Hear About The Lich by +1. This will allow you to get more Ancient Coins, but only if you can reach that level.": "提高“听说巫妖”的最高等级+1。这将允许你获得更多的古币，但前提是你能达到那个级别。",
    "Increases the Focus Mult by +1 (for a total of 3)": "增加焦点组合+1（总共3点）",
    "Initiative": "主动",
    "Instinct": "本能",
    "Invest": "投资",
    "It is recommended to spend your Ancient Coins before you start a new life. They provide no benefit except to buy upgrades, and can only be spent now.": "建议在你开始新生活之前花掉你的古币。除了购买升级外，它们不能提供任何好处，并且只能现在消费。",
    "It's time to cast some real magic!": "是时候施展真正的魔法了！",
    "Keep 20% of your Focus Loop Bonus when you use the Amulet": "当你使用护身符时，保持20%的焦点循环加成",
    "Kite The Abomination": "讨厌的风筝",
    "Learn exact legacy/AC gained in KTL before switching Overclock targets: 500 SC": "在切换超频目标之前，了解在KTL中获得的确切遗物/古币: 500 灵魂币",
    "Levels update while in zoomed-out mode now": "关卡在缩小模式下更新",
    "Maximum Focus bars +1 (up to 4): 1k SC each": "最大聚焦条+1（最多4条）：每个1k 灵魂币",
    "Momentum Taken = 1% of Current Momentum.": "获得的动量=当前动量的1%。",
    "Momentum Taken = 10% of Current Momentum.": "获得的动量=当前动量的10%。",
    "Momentum Taken = Current Momentum * Tier Mult.": "获得的动量=当前动量*层数。",
    "Momentum was taken from this action, converted to": "动量从这个动作中获得，转化为",
    "Motivation generation is increased by 25%": "动力生成增加25%",
    "My discord to discuss everything is here:": "我要讨论的一切都在这里：",
    "No AI was used in the writing of the story, and no AI-art will be added to the game.": "在故事编写中没有使用AI，也不会添加AI图像到游戏中。",
    "On unlock and level, reveal a new action.": "在解锁和升级时，显示一个新动作。",
    "On unlock, +1 Ancient Coins.": "解锁时+1古币",
    "On unlock, +1 max level for Body Awareness.": "解锁时，身体意识最大等级1级。",
    "On unlock, +1 max level for Meet Grumpy Hermit.": "解锁时，遇见暴躁隐士最大等级+1。",
    "On unlock, +1 max level for Remember.": "解锁后，记忆的最大等级增加1。",
    "On unlock, +13 Ancient Coins. This amount is multiplied by Hear About The Lich's level.": "解锁时，+13个古币这个数量乘以巫妖的等级。",
    "On unlock, +21 Ancient Coins. This amount is multiplied by Hear About The Lich's level.": "解锁时，+21个古币这个数量乘以巫妖的等级。",
    "On unlock, +3 max level for Body Awareness.": "解锁时，身体意识最大等级增加3级。",
    "On unlock, +4 max levels for Body Awareness.": "解锁时，身体意识最大等级增加4级。",
    "On unlock, +5 Ancient Coins. This amount is multiplied by Hear About The Lich's level.": "解锁时，+5古币这个数量乘以巫妖的等级。",
    "On unlock, +7 Ancient Coins.": "解锁时，+7个古币。",
    "On unlock, +8 Ancient Coins. This amount is multiplied by Hear About The Lich's level.": "解锁时，+8个古币。这个数量乘以巫妖的等级。",
    "On unlock, open Magic and +1 Legacy.": "解锁后，打开魔法和+1遗物。",
    "On unlock, reveal a new action.": "解锁时，显示一个新动作。",
    "On unlock, set job to Chimney Sweep for a base wage of $100.": "解锁时，设置工作为烟囱清扫，基本工资为 $100。",
    "On unlock, set job to Guild Receptionist for a base wage of $500k.": "解锁时，设置工作为公会接待员，基本工资为 $500k。",
    "On unlock, set job to Handyman for a base wage of $2000.": "解锁时，设定工作为杂工，基本工资为 $2000。",
    "On unlock, set job to messenger for a base wage of $4m.": "解锁后，将工作设置为信使，基本工资为 $4m。",
    "On unlock, set job to Odd Jobs Laborer for a base wage of $20.": "解锁时，将工作设置为零工工人，基本工资为 $20。",
    "On unlock, set job to storyTeller for a base wage of $20t.": "解锁时，将工作设置为说书人，基本工资为 $20t。",
    "On unlock, set job to Tavern Helper for a base wage of $20000.": "解锁时，将工作设置为酒馆助手，基本工资为 $20000。",
    "On unlock, set job to townCrier for a base wage of $250b.": "解锁时，将工作设置为城镇宣传员，基本工资为 $250b。",
    "Options and Info Menu": "选项和信息菜单",
    "Options keep on refresh": "选项保持刷新",
    "Overclock gains a flat +5 momentum per second.": "超频每秒获得+5的动量。",
    "Overclock Targeting The Lich": "超频瞄准巫妖",
    "Overclock Targeting the Lich now runs on first tick after KTL": "超频瞄准巫妖现在在KTL后的第一秒运行",
    "Pester Hermit For Secrets": "纠缠隐士获取秘密",
    "Practical Magic": "超异能快感",
    "Prepare External Spells": "准备外部咒语",
    "Prepare Internal Spells": "准备内部咒语",
    "Present The Offering": "提交发行",
    "Prevented hotkeys while the menu is open": "防止菜单打开时使用热键",
    "progress required to complete": "完成所需的进度",
    "Protect The Sunstone": "保护太阳石",
    "Read Old Philosophy": "阅读古代哲学",
    "Read Old Poetry": "读古诗",
    "Read Old Prophecies": "阅读古老的预言",
    "Read Old Religious Texts": "阅读古老的宗教典籍",
    "Read Old Stories": "读旧故事",
    "Recommended to start. ": "建议启动。",
    "Remember Friends": "记得朋友",
    "Remember The War": "记住战争",
    "Remove Wards": "删除病房",
    "Removed the + in e for scientific notation": "删除了科学符号e中的+",
    "Requires 1e12 Momentum Taken to function.": "需要1e12动量才能发挥作用。",
    "Restore Equipment": "恢复设备",
    "Review Old Memories": "回顾过去的记忆",
    "Scott and you keep talking for a while, and then he mentions that he overheard you've been doing good work, and has more people to recommend you to.\n": "斯科特和你继续聊了一会儿，然后他提到他无意中听到你的工作做得很好，并且有更多的人可以推荐你",
    "Second Highest level (2x up to):": "第二高等级（最多2x）：",
    "Sending resources caps at 100% now, not 10%. Removed info about it. This hopefully reduces confusion with the focus bars. TBD if this is too much": "发送资源上限现在是100%，而不是10%。删除了相关信息。这有望减少焦点条的混淆。如果这太多了，待定",
    "Set Overclock's Target: Kill the Lich!": "设定超频的目标：杀死巫妖！",
    "Sharpen Weapons": "提高武器",
    "Shatter Phylactery": "粉碎护符",
    "Shatter Traps": "粉碎的陷阱",
    "Shelter": "避难所",
    "Show All 0 and All 100 Buttons": "显示所有0和所有100按钮",
    "Show Attribute Upgrades": "显示属性升级",
    "Show Completed Upgrades": "显示已完成的升级",
    "Show Increase/Decrease Ratio": "显示增减比",
    "Show Total Downstream": "显示下游总量",
    "Show Unaffordable": "显示无法负担",
    "Silence Death Chanters": "沉默死亡颂歌",
    "Silence Doom Scribe": "沉默毁灭抄写员",
    "Socialize": "社交",
    "Some Generator's Exp to gain now updates fluidly.": "一些生成器的经验获得现在更新流畅。",
    "Something Must Be Done": "必须做点什么",
    "spark": "火花",
    "Spark": "火花",
    "Spark Mana": "火花法力",
    "Spark was added to Spark Mana.": "火花被添加到火花魔法中。",
    "Spark was taken from Spark Mana, converted to": "星火从星火法力中移除，转化为",
    "Special Resource Bonuses:": "特殊资源奖励：",
    "spell power, and Hear About The Lich level": "法术能力和听说巫妖等级",
    "Tip #11: Hesitation": "提示 #11：犹豫",
    "Unhook Sacrificial Cages": "解开献祭笼",
    "Unlock option for Bonus Speed to go x10: 100 SC": "解锁选项的奖励速度去x10: 100 SC",
    "Visit Shrine Behind Waterfall": "参观瀑布后的神殿",
    "want": "想要",
    "What did they just say?": "他们刚刚说了什么？",
    "What do you want to know?": "你想知道什么？",
    "When using amulet, the action menus will work immediately after": "当使用护身符时，动作菜单将立即工作",
    "As soon as you step in sight of your new boss, you immediately decide that this can't be all there is. \n        You decide to get some clothes for the occasion, and go find where that scent came from. A higher wage will let you get those things easier.": "一旦你看到你的新老板，你就会立刻决定这不可能是全部。你决定为这个场合买些衣服，然后去找那股气味是从哪里来的。更高的工资会让你更容易得到这些东西。",
    "The Make Money action is unlocked, south of Overclock. It uses a different formula to consume momentum - found in Info - so figure out what sending ratio works for you.\n        The formula needs about 250 momentum to start giving valid amounts, and then the generated value adds exp to \n        Make Money and gold to Spend Money. From there, gold is treated the same Momentum in the way it works on Spend Money.": "超频以南的“赚钱”动作已解锁。它使用一个不同的公式来消耗动量-在信息中找到-所以找出适合你的发送比例。这个公式需要大约250动量才能开始提供有效的数值，然后生成的数值会将经验值添加到n中。从这里开始，金币就像在《花钱》中一样被视为动量。",
    "Some actions have max levels, first shown with \"Level 0 / 10\". When the level is at the max (in this case 10), \n        momentum will no longer be consumed - this means it will send 100% of the resource onwards without taking any.": "有些动作有最高等级，首先显示为“等级0 / 10”。当关卡达到最大值时（在本例中为10），\n动量将不再被消耗——这意味着它将发送100%的资源而不占用任何资源。",
    "\"Laborer required for odd jobs. Starting wage $10. Ask Grelt.\"": "“招聘临时工。起薪是$10。问葛蕾特吧。”",
    "2 new Actions unlocked!": "2个新动作解锁！",
    "Actions also have an efficiency, which is improved by the blue Attributes for that action.": "操作还具有效率，该效率通过该操作的蓝色属性得到提高。",
    "ATTENTION:": "注意:",
    "Blue: Increases efficiency. For actions, efficiency is the send and consume rate. For generators, it is the generator speed, generator amount, and send rate.": "蓝色：提高效率。对于动作，效率是发送和消耗的速率。对于发电机，它是发电机转速、发电机数量和发送速率。",
    "Come down to JOHN'S TRAINING CENTER and I will make you STRONG.": "到约翰的训练中心来，我会让你变得强壮。",
    "Do you need BRAIN MUSCLES to remember what I tell you the first time?": "你需要大脑肌肉来记住我第一次告诉你的东西吗？",
    "Do you need HEART MUSCLES to GIVE YOU THE POWER?": "你需要心脏肌肉来给你力量吗？",
    "Do you need LEG MUSCLES to RUN FOREVER?": "你需要腿部肌肉才能永远跑下去吗？",
    "Each action has a tier. Tier 0 is a default send rate of 10%, Tier 1 is 1%, Tier 2 is .1%, etc.": "每个动作都有一个层次。第0层默认发送率为10%，第1层为1%，第2层为0.1%，以此类推。",
    "Generators do not consume resources automatically. Read their info for more.": "生成器不会自动消耗资源。阅读他们的信息了解更多。",
    "Green: Adds the attribute on level": "绿色：在等级上增加属性",
    "It is tucked behind the others, so you did not spot it at first. It is short, and untitled:": "它藏在其他的后面，所以你一开始没有发现它。它很短，没有标题；",
    "Many posters are advertising a market. Maybe you should check that out.": "许多海报都在为一个市场做广告。也许你应该去看看。",
    "New will become visible when you reach various hidden milestones, but more will be visible at once later. For now, \n        get reflect to levels 4 and 6 to unlock two new actions!": "当你达到各种隐藏的里程碑时，新的将变得可见，但更多的将在稍后立即可见。现在，\n得到反映到等级4和6解锁两个新的行动！",
    "Purple: Reduces the progress required to complete if it is an action, reduces exp required to level if it is a generator": "紫色：如果它是一个行动，减少完成所需的进度，如果它是一个生成器，减少升级所需的经验",
    "Rate of sending = tier mult * efficiency * slider bar %.": "发送速率=多层*效率*滑条%。",
    "Scott showed you how to make money, and so the Current Job is set to Helping Scott with Chores, with a wage of $1.": "斯科特向你展示了如何赚钱，所以现在的工作是帮助斯科特做家务，工资是$1。",
    "The send rate affects how resources are moved around as well as the consumption rate (if it is not a generator).": "发送速率影响资源的移动方式以及消耗率（如果它不是生成器）。",
    "There will generally be an obvious goal to work towards for more unlocks.": "通常会有一个明显的目标去争取更多的解锁。",
    "To make a lot more money, get a better job at the outpost (check notice board level 3).": "为了赚更多的钱，在前哨找到一份更好的工作（查看第3级公告板）。",
    "When an action is max level and there is no incoming or outgoing of its resource, it will dim.": "当一个动作达到最高级别并且没有输入或输出资源时，它将变暗。",
    "When an action is max level, it will get a MAX LEVEL stamp and the background color of the action will change based on its resource.": "当一个动作达到最大级别时，它将获得一个最大级别标记，并且该动作的背景颜色将根据其资源而改变。",
    "> Resume": "> 返回",
    "If the Action is a generator (like Overclock), increases the action power, which is how much it generates e.g. Overclock gets x1.1 multiplicative to action power per level. Details are in Info menu.": "如果动作是一个生成器（如超频），则增加动作功率，即它产生的数量，例如，超频每级的动作功率乘以x1.1。详细信息在信息菜单。",
    "Attributes, which are the way actions affect each other - details are in Info menu.": "属性，这是行动相互影响的方式-详细信息在信息菜单中。",
    "Increased progress/exp requirements, described by the greyed-out text in their bars.": "增加进度/经验要求，在条形图中用灰色文字描述。",
    "Tip #10: Changing Colors": "提示 #10：改变颜色",
    "Tip #13: Making Money": "提示 #13：赚钱",
    "Tip #14: NOTICE - Market Ads": "提示 #14：通知-市场广告",
    "Tip #15: NOTICE - Report for Training": "提示 #15：通知-训练报告",
    "Tip #16: NOTICE - A hidden notice": "提示 #16：通知——隐藏的通知",
    "Tip #17: You Need A Break": "提示 #17：你需要休息",
    "Tip #6: Attributes": "提示 #6：属性",
    "Tip #7: Game Math on Sending": "提示 #7：关于发送的游戏数学",
    "Tip #8: Finding New Actions": "提示 #8：寻找新的行动",
    "Tip #9: Max Level": "提示 #9：最大关卡",
    "Disable Bonus Speed": "禁用奖励速度",
    "Tip #5: Exp and Leveling": "提示 #5: 经验和等级",
    "Sort by Cost": "按成本排序",
    "Use Advanced Downstream Sliders": "使用高级下游滑块",
    "Open Log": "打开日志",
    "Automation": "自动化",
    "! button under Hear About the Lich now is hidden when in the Kill the Lich game mode. It also remains visible when zoomed out.": "！ 在“杀死巫妖”模式下，“听到巫妖”下的按钮将被隐藏。它在缩小时也仍然可见。",
    "(Legacy, Time)": "（遗产，时间）",
    "(Legacy Gained, Ancient Coin Gained)": "（获得的遗产，获得的古币）",
    "(Warning: will adjust to the nearest option when turning off)": "（警告：关闭时将调整到最近的选项）",
    "Backstory": "背景故事",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "FPS:": "FPS:",
    "o": "o",
    "NaN": "NaN",
    "asdf": "asdf",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "\n        ": "\n        ",
    "\n    ": "\n    ",
    "\n\t\t\t": "\n\t\t\t",
    "\n\t\t\t\t": "\n\t\t\t\t",
    "\n    ": "\n    ",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Magic ": "魔法 ",
    "Total Reduction = ": "总减少量 = ",
    "% efficiency": "% 效率",
    "% instability": "% 不稳定性",
    "Kill The Lich": "杀死巫妖",
    "Kill the Lich": "杀死巫妖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Soul Coins": "灵魂币",
    "Soul Coins (SC)": "灵魂币 (SC)",
    "As I observed the various actions that I had thus felt out, I realized that Reflect and Distill Insight had some whirls \nI could smooth out by controlling their spins into joining the river quicker.": "当我观察到各种各样的动作时，我意识到“反射”和“提炼洞察力”有一些旋涡，我可以通过控制它们的旋涡来更快地加入河流。",
    "Overclock was a storm, and difficult for me to fully access. I didn't quite understand, but feeling out those complicated ever-changing knots,\n it also sparked the tip of a memory. I had been confused - why was this familiar?\n": "超频是一场风暴，对我来说很难完全访问。我不太明白，但摸出那些复杂多变的结，也勾起了记忆的一角。我一直很困惑——为什么这很熟悉？\n",
    "Going with the flow of my ability, it carried me out of the fire, out of the war, out of danger, out of caution, and \n    into Safety. Over the next few weeks, I continued the repeated miraculous luck, though the effect diminished over time.\n    From finding abandoned horses and supplies, to hearing just the right thing in a conversation, to staying in just the \n    right spot to not be discovered while I slept. Ultimately, [Get Somewhere Safe] had gotten me... Somewhere Safe.": "随着我的能力的流动，它带我离开了火灾，离开了战争，离开了危险，离开了谨慎，进入了安全。在接下来的几个星期里，我继续重复着这种神奇的运气，尽管这种效果随着时间的推移而减弱。从寻找被遗弃的马匹和物资，到在谈话中听到正确的事情，到呆在正确的地方，在我睡觉的时候不被发现。最终，[去安全的地方]让我……安全的地方。",
    "The Overclock action gets progress automatically, and when it completes it generates your first resource: Momentum. \n        The gameplay is to change (using the sliders) the percentage of send rate of each action's resource to their downstream actions.": "超频动作会自动取得进展，当它完成时，它会生成你的第一个资源：动量。游戏玩法是改变（使用滑块）每个行动的资源发送率的百分比到他们的下游行动。",
    "\"Do this on your own time, but later you should try meditation. Write things down if you have trouble with it.\"": "“在你自己的时间里做这件事，但之后你应该尝试冥想。如果遇到困难，就把它写下来。”",
    "He was surprisingly less grumpy as he said it, and with a look at my face his scowl returned.": "他说这话的时候，气色出奇地缓和了，看了看我的脸，他的怒容又回来了。",
    "I was terrified at the idea of trying to go against the lich, but I thought of how many lives had been sacrificed \n        and ruined at the altar of this monstrosity's rampage. In what felt like such a short time, Overclock had grown far \n        beyond what I had achieved to Get Safe, and I was ready; I could bend fate in my favor to kill the lich.": "一想到要反抗巫妖，我就感到害怕，但我又想到有多少生命在这个怪物的横冲直撞的祭坛上被牺牲和毁灭。在这么短的时间里，超频已经远远超出了我所能达到的安全水平，我已经准备好了；我可以改变命运，杀死巫妖。",
    "I'm looking for feedback on the pricing for when the game lives on steam, outlined below.": "我正在寻找关于游戏在steam上的定价反馈，如下所述。",
    "It mattered little. There was a lich, it was coming for all humanity, and I was prepared.": "这无关紧要。有个巫妖要来追杀全人类，我准备好了。",
    "On Level up:": "当升级时:",
    "So, I changed the target of Overclock, from itself to a new target: Kill the Lich. I felt my thoughts collapse, no longer held up \n        by the artificial momentum. I became focused, with only a single goal in mind: letting my ability life my legs, move my mouth, and swing my sword. \n        For better or worse, I was along for the ride.": "所以，我改变了超频的目标，从它自己变成了一个新的目标：杀死巫妖。我感到我的思想崩溃了，再也没有人为的动力支撑着我。我变得专注，心中只有一个目标：让我的能力活在我的腿上，动我的嘴，挥舞我的剑。不管是好是坏，我一直都在。",
    "This time, however, I was going to go prepared; I knew Fate could only bend so far at a time. I had just received magic,\n        and knew that all I needed was to show I had the power to help, and the War for Life would let me join.": "然而，这一次，我准备去；我知道命运一次只能改变这么多。我刚刚获得了魔法，我知道我所需要的就是证明我有能力提供帮助，而生命之战会让我加入。",
    "Unlocks new actions with each level.": "每级解锁新动作。",
    "Increase wage +50%.": "增加工资50%。",
    "Increase wage +50%": "增加工资50%",
    "And so, after putting it off as long as possible with as many chores and preparations done I could think of, I stopped. I sat on the floor. I breathed. I let it in.": "所以，在尽可能拖延时间，尽我所能做了许多家务和准备工作之后，我停下来了。我坐在地板上。我呼吸。我让它进来了。",
    "The first step in how to create your own magic: Stay Still. I had been trying not to do this, but with the \n        instructions of the hermit, I found new cause to try again. I don't hide my struggle with the task, and the old man scoffs.": "如何创造自己的魔力的第一步：保持静止。我一直试图不这样做，但在隐士的指示下，我找到了再次尝试的新理由。我没有掩饰我对这项任务的挣扎，老人嘲笑我。",
    "I was tapping my pen on my chin when I suddenly focused on the sensation - was there a way to use \nmy momentum on my own proprioception? To mindfully move each of my muscles at all times would be incredible! I could craft such fine tools!": "当我用笔在下巴上轻敲时，我突然专注于这种感觉——有没有一种方法可以利用我的动量来实现我自己的本体感觉？每时每刻都有意识地活动我的每一块肌肉将是不可思议的！我可以制作这么好的工具！",
    "I started realizing the difficulties of understanding what was changing, so I started taking notes. \nAt first, I recorded the patterns, but as it helped me understand exactly how Overclock was changing: it was \nsubstantially growing. I wondered how far this could go.": "我开始意识到理解变化是多么困难，所以我开始做笔记。首先，我记录了这些模式，但它帮助我准确地了解了超频是如何变化的：它没有实质性地增长。我想知道这能走多远。",
    "When the progress bar is full, an action will gain 1 exp (for now) until it levels up. On level up, the stat will give:": "当进度条填满时，一个行动将获得1个经验值，直到升级。升级后，该属性将给出：",
    "What was the point? I should have handled myself first.": "有什么意义呢？我应该先处理好自己的。",
    " (level + 1) Legacy on complete.": " (等级 + 1) 遗物在完成时.",
    "As I finally made that connection, I also realized that it couldn't go on.": "当我最终建立起这种联系时，我也意识到这种关系不能继续下去了。",
    "Amount added = 10% of Fear * Efficiency per complete.": "数量增加 = 10% 恐惧 * 效率 每次完成.",
    "At first, I simply sat down and closed my eyes, and tried to feel, or see, or sense in any way something that was possible.": "起初，我只是坐下来，闭上眼睛，试着去感觉、去看、去感觉任何可能的东西。",
    "An insight quickly arose, gained as I became more aware of the currents of momentum flowing through my soul. \nI noticed, in those currents, that some was splashing over.": "当我越来越意识到灵魂中涌动的动力之流时，一种洞察力很快就产生了。我注意到，在那些水流中，有一些溅了出来。",
    "Almost immediately, my ability triggered successfully on yet another surprising option - \nthe ability to understand what I was doing, to distill insight out of the complicated signals coming through.": "几乎立刻，我的能力成功地触发了另一个令人惊讶的选择——理解我在做什么的能力，从纷杂的信号中提炼出洞察力的能力。",
    "A lich is a creature of bones, dark magic, and myth, occuring rarely in history and causing catastrophes each time. 13 years ago, the Emperor Brithan of Sovvgor had used one of his Talents to kill a lich far to the north, but not without great cost.\n Though this lich and his evil forces had been vanquished, there was a curse on the land. For hundreds of miles - which mostly included wasteland and the majority of the Empire of Sovvgor - those who had Talents could not use them. \n Though they told us the cause, it was a bitter pill to swallow for all of the country's citizens. Talents were our magic, our connection to the idea that though the world is big, we have our place in it.": "巫妖是一种由骨头、黑魔法和神话组成的生物，在历史上很少出现，每次都造成灾难。13年前，索夫戈尔的布里坦皇帝用他的天赋之一杀死了远在北方的巫妖，但付出了巨大的代价。虽然这个巫妖和他的邪恶势力已经被征服了，但这片土地上仍有一个诅咒。在数百英里的范围内——其中大部分是荒地和索夫戈尔帝国的大部分地区——那些拥有天赋的人无法使用天赋。尽管他们告诉了我们原因，但对这个国家的所有公民来说，这是一颗难以下咽的苦果。天赋是我们的魔力，是我们与“世界很大，但我们在其中有自己的位置”这一理念的联系。",
    "\"Choose a valid target; get a little more out of it\" is the Description on my ability Overclock. Abilities are given intuitively, \nand the Description was part of that intuitive understanding, given as soon as one has understood all of the words within the Description. \nOverclock works by using the concept of momentum to improve the target over time. The target will be denied unless it meets the criteria, \nwhich is any type of action you can do over and over until you get better at it.": "\"选择一个有效的目标；得到更多的东西\”是对我的能力超频的描述。能力是直觉赋予的，而描述是这种直觉理解的一部分，一旦理解了描述中的所有单词，就会赋予能力。\n超频的工作原理是利用动量的概念来随着时间的推移改善目标。目标将被拒绝，除非它符合标准，即任何类型的行动，你可以反复做，直到你做得更好。",
    "\"Oh wow, you actually want to know about me? Well, I've been here a long time.\"": "“哦，哇，你真的想了解我吗？”嗯，我在这里已经很长时间了。”",
    ". I would really appreciate hearing about your experience, \n        and how you felt while playing! \n        You can also talk about the game in the discord with others, and share strategies.": "。我真的很想听听你的经历，\n和你在玩游戏时的感受！你也可以在不和中与他人谈论游戏，并分享策略。",
    "This was more than I ever anticipated. I had targeted Overclock to itself so that I would be prepared so that the next \ntime a threat came along, I would have a large pool of a fate-bending resource, and therefore - at least once - be strong enough \nto save more than only myself. Maybe then, I could learn to find some measure of peace.": "这超出了我的预期。我把超频设定为自己的目标，这样我就能做好准备，这样当下一次威胁出现时，我就能拥有一大批扭转命运的资源，因此——至少一次——我就能强大到足以拯救更多的人，而不仅仅是我自己。也许到那时，我就能学会找到某种程度的平静。",
    "That feeling, that concept - momentum - had been spilling over somehow from when I had the target set to itself. \nIt felt as if there was a spinning vortex of movement, with splashes leaking. Momentum had \nstarted to apply itself in small ways to anything I started doing that fit the targeting criteria, and the momentum had \nme continue doing whatever it was, helping me to do so as long as I needed.": "那种感觉，那种概念——动量——不知怎么地从我设定目标的时候就开始了。感觉好像有一个旋转的运动漩涡，溅起水花。动力已经开始在我开始做的任何符合目标标准的事情上以微小的方式发挥作用，动力让我继续做任何事情，只要我需要，它就会帮助我这样做。",
    "My ability is Overclock, and the simple description of it is \"Choose a valid target; get a little more out of it\". \nI used to change Overclock's target a dozen times a day, enjoying the extra \"skips\" in my \"steps\" as it hurried me along, so-to-speak. \nWhen, without warning, the curse made all abilities in the country inert and useless, my ability was locked with a Target of [Get Somewhere Safe]. \nFor a few peaceful years it was just something to grieve and adjust to. However, as Sovvgor was betrayed by our greedy neighbors Gryndall, \nand as I was conscripted and armed and trained as a soldier, the locked target of my Description instead became my mantra and my burden. \nIt was forever locked on the one thing I desired, and this was a rather painful irony I had to overcome on my march towards certain death.": "我的能力是超频，简单来说就是“选择一个有效的目标；从中得到更多的东西”。我过去常常一天改变超频的目标十几次，享受着我“步伐”中额外的“跳跃”，可以说，因为它让我走得更快。在没有任何警告的情况下，诅咒使这个国家的所有技能都变得惰性和无用，我的技能被锁定在一个[安全的地方]的目标上。在平静的几年里，这只是一件悲伤和适应的事情。然而，随着我们贪婪的邻居格林多背叛了索夫戈，而当我被征召入伍、武装起来、训练成为一名士兵时，我描述的锁定目标反而成了我的咒语和负担。它永远锁定在我想要的一件事上，这是一个相当痛苦的讽刺，我必须在走向死亡的道路上克服它。",
    "The Ashmarch, is what they eventually called it, for what was left of the land. They killed all but a handful of men \nduring the journey itself, experimenting with how the various long range ablities, summons, and devils lasted into our \ncursed land. We were defenseless, but we marched onward, for it was our only option. Many horrors were on the battlefield those three days. Too many.": "阿什马奇，这是他们最终的称呼，因为剩下的土地。他们在旅途中杀死了几乎所有的人，除了少数几个人，以试验各种远程能力、召唤和恶魔是如何持续到我们的诅咒之地的。我们毫无防备，但我们继续前进，因为这是我们唯一的选择。那三天战场上发生了许多恐怖事件。太多了。",
    "The Gryndallan betrayers didn't let us reach the edge of the curse. Our Talents were never unlocked by walking out. \nI think they only left us alive at the edge hoping to be entertained with the last of our impotent revenge. \nThey wanted us to burn out in front of them, but they rapidly lost interest when they only found injured men waiting for their turn to die. We were quickly captured.": "格林达伦的叛徒没能让我们到达诅咒的边缘。我们的才能永远不会因为离开而被释放。我想他们只是把我们留在悬崖边，希望用我们无力的最后一次复仇来娱乐我们。他们想让我们在他们面前被烧死，但当他们发现只有受伤的人等着死去时，他们很快就失去了兴趣。我们很快就被抓住了。",
    "I adjusted, and simply did more each day. For a while it lasted, but I was well on my second pile of firewood when I realized I had more than I reasonably could use. I let myself think about why. \n Firewood kept stacking up because I was trying to use the forced movement coming out of my ablity, so that it didn't force me to do what I know I needed to.": "我调整了一下，每天做得更多。这种情况持续了一段时间，但当我意识到我有太多的柴火时，我已经在第二堆柴火上了。我让自己想想为什么。\n柴火一直在堆积，因为我试图用我的能力来强迫移动，这样它就不会强迫我做我知道我需要做的事情。",
    "After some focus, I felt a new conceptual river open up from Overclock, flowing into the idea of being aware of myself. \nFor a moment, it was incredible to realize that I could expand this way, but rapidly I felt I hit my limit of comprehension.": "经过一段时间的专注，我感到一条新的概念之河从超频中打开，流入意识到自己的想法。有那么一刻，我难以置信地意识到我可以这样扩展，但很快我就觉得我达到了理解的极限。",
    "It was only when my legs stopped carrying me to the next task, and my hands stayed idle at my sides, \nthat I finally realized the only reason I was moving at all was Overclock churning through it's 13 year buildup of momentum. \nBut then - all at once - the remainder was gone. I had to find my own reasons for moving forward. At first, I stood there for hours, \nfrozen with it all, thinking of everything and nothing, before finally simply using my senses to discover what my body had done while I wasn't paying attention.": "直到我的腿不再带我去做下一个任务，我的手也无所事事地放在身体两侧时，我才终于意识到，我还在动的唯一原因是超频在13年积累的动力中翻腾。但是，突然间，剩下的都不见了。我必须找到自己继续前进的理由。一开始，我在那里站了好几个小时，完全被这一切惊呆了，什么都想，什么都没想，最后我只是用我的感官去发现我的身体在我不注意的时候做了什么。",
    "Still, the newfound awareness had me desire to move around; I just had to find a purpose to do so.\n": "然而，新发现的意识让我渴望四处走动；我只需要找到这样做的目的。\n",
    "As long as I stated doing something potentially targetable - even without me realizing it - the conceptual \"spillover\" from the vortex would latch on.": "只要我声明要做一些有潜在目标的事情——即使我没有意识到这一点——漩涡的概念“溢出效应”就会出现。",
    "As the days passed however, I eventually came to realize I was growing sharper in my focus as I went \nabout my daily chores, though I was also having increasing trouble sitting still after the day's work. \nAfter a few weeks of solitude and focusing on nothing but survival and preparation for winter - blessed stagnancy -\n it became easy to point out the change: my ability was doing something. Overclock was somehow making me move, making me think. \n It seemed the choice was still mine for which of those I could do, and it made my choice obvious; I didn't want to think, right now.": "然而，随着日子一天天过去，我终于意识到，在处理日常琐事时，我的注意力越来越集中，尽管在一天的工作结束后，我也越来越难以坐着不动。经过几个星期的孤独，除了生存和为冬天做准备——幸运的停滞——我很容易指出变化：我的能力在做一些事情。超频让我动起来，让我思考。这似乎仍然是我的选择，我可以做哪一个，这使我的选择很明显；我现在不想多想。",
    "As the Gryndallans were deciding what to do with us, the situation suddenly changed: after 13 years of our abilities\n being frozen and inert, they suddenly sprang alive and became active! Later we would learn this was the Gryndallans who, in an incident of timing,\n  had killed our Emperor too early, but in the moment we thought it fortune smiling upon us and seized the moment. My Overclock had also sprung to life,\n   and with 13 years of buildup, fate herself bent to see my Target true. My escape was a circus of coincidences\n    and unforseen Talent interactions, but I got out - alone. My Talent, with the buildup, had become more than the skip in my steps; \n    it was the whole step, and the knowledge of when and where to do so as well.": "就在格林达拉人决定如何处置我们的时候，情况突然发生了变化：在我们的能力被冻结和惰性了13年之后，它们突然变得活跃起来！后来我们才知道，这是格林达拉家的人，因为时间的原因，他过早地杀死了我们的皇帝，但在我们认为幸运向我们微笑的那一刻，我们抓住了这个机会。我的超频（Overclock）也活了起来，经过13年的积累，命运终于让我的目标成真了。我的逃脱是一场充满巧合和意想不到的“天才”互动的马戏，但我逃脱了——独自一人。我的才能，随着日积月累，已经超过了我脚步中的跳跃；这是整个步骤，以及何时何地这样做的知识。",
    "At first, I put this choice out of my mind - it was only to remember it for comfort when I awoke in the night and little more. \nThis had been a choice to have a fate-bending escape option prepared, should I need it, for however the future was shaped. \nUnder the Emperor's curse, I had gotten used to daily life without it, and so it was fine - comforting, even - to keep the ability in reserve.": "起初，我把这个选择抛在脑后——只是为了在夜里醒来时想起它来安慰自己，仅此而已。这是一个选择，如果我需要的话，我已经准备好了一个改变命运的逃跑选择，不管未来是如何形成的。在皇帝的诅咒下，我已经习惯了没有这种能力的日常生活，所以保留这种能力是很好的——甚至是令人欣慰的。",
    "But to my surprise, it was the act of looking itself that I felt the momentum latch onto. \nI gained awareness - I was starting to understand the nature of how my ability was influencing things. \nHowever, as the monstrous complexity of what this meant started to hit me, I realized this would be a long journey indeed.": "但令我惊讶的是，我感到动力的是看的行为本身。我开始意识到——我开始理解我的能力是如何影响事物的本质。然而，当我开始意识到这意味着可怕的复杂性时，我意识到这将是一段漫长的旅程。",
    "Gryndal used to be our former ally, a country in the west we have known for many decades. \nBut they smelled blood in the water, and who can say they would do different? They forced a diplomatic incident that \ndemanded a response, the lords shouted a lot, and off to war us conscripts went. Originally, the hope was that we would \nescape the curse's domain and use our Talents again, and re-equip and re-train accordingly. We had blacksmiths and enchanters! \nThe hope was that their honor would give us at least some semblance of a fair fight. How disgustingly optimistic.": "格林达尔曾经是我们的盟友，一个我们认识了几十年的西方国家。但他们闻到了水里的血腥味，谁能说他们会有不同的做法呢？他们制造了一个需要回应的外交事件，领主们大喊大叫，我们的义务兵去了战场。最初，我们希望我们能逃离诅咒的领域，再次使用我们的天赋，并相应地重新装备和重新训练。我们有铁匠和魔法师！我们希望他们的荣誉至少能给我们带来一些公平竞争的表象。多么令人厌恶的乐观啊。",
    "I could exist here, and it would be Safe. And for a few weeks, I did just that while I settled in. But the nightmares got stronger, \nand my paranoia was bleeding over into affecting my waking moments. In a move to give myself an option, I decided to attempt \nto replicate the buildup of 13 years by changing Overclock's target. To some surprise, I set it successfully, and the Target of Overclock was... [Overclock].": "我可以在这里生存，这里会很安全。有几个星期，我就是这样安顿下来的。但噩梦越来越强烈，我的妄想症开始影响我醒着的时候。为了给自己一个选择，我决定尝试通过改变超频的目标来复制13年的积累。令我惊讶的是，我设置成功了，超频的目标是……(超频)。",
    "I needed to experiment more - was there more I could pull out of this?\n": "我需要做更多的实验——我能从中得出更多的结论吗？\n",
    "I observed the spillage - where would it go? - and found that, eventually, it always rejoined the current. Now that I was \nlooking for it, I realized my other actions that momentum had latched onto had much more violent currents and eddies, \nwhirling in place and creating knots of movement, hindering transference.": "我观察了泄漏——它会去哪里？——并发现，最终，它总会重新加入洋流。现在我正在寻找它，我意识到我的其他行动，由动力锁定有更激烈的水流和漩涡，在原地旋转，造成运动的结，阻碍转移。",
    "I try not to think about it.": "我试着不去想它。",
    "I was Safe, and I knew it to be true - I was in a recently abandoned hunter's cabin, having caught his widow traveling \nthe other way, who said I could have it. I had the tools and supplies to let me survive on the wilderness around me as \nlong as I needed. I was not in my home in Sovvgor, nor in the betrayer Gryndal's lands, but instead the southern country Osric. \nOsric's King had been observing the news in the north with caution, but had not interfered.": "我很安全，而且我知道这是真的——我在一个最近被遗弃的猎人的小屋里，撞见他的寡妇从另一个方向来，她说我可以拥有它。只要我需要，我有工具和补给让我在周围的荒野中生存下去。我不在我在索夫戈尔的家，也不在背叛者格林达尔的领地，而是在南方的奥斯里克。诺斯里克的国王一直在小心翼翼地观察北方的消息，但没有干预。",
    "It was as I was writing while continuing to work the knots in my soul that I realized I was easily doing multiple things at once.\nMy thoughts felt split, yet not incomplete; I had the attention to give to both things at once. What else could I do at the same time?\n": "当我一边写作，一边继续解决我灵魂中的结时，我意识到我很容易同时做多件事。我的思想是分裂的，但不是完整的；我必须同时注意这两件事。我还能同时做什么？\ n",
    "| Wage: $": "| 工资: $",
    "max levels for Harness Overflow.": "最大等级对于利用溢出。",
    "max level for Meditate.": "最大等级对于冥想。",
    "As I finally made that connection, I realized that the only way forward was through. And so, after putting it off as long as possible, I stopped. I sat on the floor. I breathed. I let it in, and reflected.": "当我最终建立起这种联系时，我意识到前进的唯一道路就是勇往直前。所以，在尽可能拖延之后，我停止了。我坐在地板上。我呼吸。我让它进来，沉思着。",
    "I started doing chores I didn't need to - piling up more firewood, cleaning my clothes more often, carving wood into furniture and decorations. For a while it lasted, but I was finishing my fourth pile of firewood when I realized I had more than I reasonably could use for the entire winter, and reconsidered how what I was doing. I let myself think about why I was pushing things out. I let myself think about who I wanted to be, and I realized I would need to think about who I was. I considered changing Overclock's target to continue to avoiding the subject, but I felt instant terror at the idea that I would be without safety - the same as any other soldier in the Ashmarch.": "我开始做一些我不需要做的家务——堆积更多的柴火，更经常地清洗我的衣服，把木头雕刻成家具和装饰品。这种情况持续了一段时间，但当我快要烧完第四堆柴火时，我意识到我的柴火远远超过了整个冬天的用量，于是我重新考虑了自己的做法。我让自己思考我为什么要把事情推出去。我让自己思考我想成为什么样的人，我意识到我需要思考我是谁。我考虑过改变“超频”的目标，继续回避这个话题，但一想到我将没有安全，我立刻感到恐惧——就像阿什玛克的其他士兵一样。",
    "My Talent is Overclock, and the simple description of it is \"Choose a valid target; get a little more out of it\". In my youth, I used to change Overclock's target a dozen times a day, enjoying the extra \"skips\" in my \"steps\" as it hurried me along, so-to-speak. I used it to ease the daily life - doing chores and travelling, mostly. As a boy of 10 years, I had been playing a game of hide and seek with my friends when, without warning, the curse fell over us and all our Talents were locked, inert, and useless. My Overclock was locked with a Target of [Get Somewhere Safe], unable to be changed, and unable to help. For a few peaceful years our new reality was something to grieve and adjust to. We pined for what could have been, as we moved on to discover who we would become instead. However, we never got the chance; our neighbors only saw the curse as a weakness to exploit.": "我的天赋是超频，它的简单描述是“选择一个有效的目标；从中得到更多的东西”。在我年轻的时候，我常常每天改变“超频”的目标十几次，享受着它在我的“脚步”中催促我前进时额外的“跳过”。我用它来缓解日常生活——主要是做家务和旅行。作为一个十岁的男孩，我一直在和朋友们玩捉迷藏的游戏，突然，在没有任何预兆的情况下，诅咒降临在我们身上，我们所有的才能都被锁住了，失去了活力，毫无用处。我的超频被锁定在[安全的地方]，无法更改，也无法提供帮助。在平静的几年里，我们的新现实让我们感到悲伤和适应。当我们继续前进，去发现我们会成为什么样的人时，我们渴望本来可以是什么样的。然而，我们从来没有机会；我们的邻居只把诅咒看作是可以利用的弱点。",
    "We were bound with rope, and kept within the cursed side. The Gryndallans debated on what to do with us: whether to bring us one a time across the border for staged duels to appease the egos of their gathered warriors, or whether it would be too large of a risk for, and they should kill us all without such theatrics. It was during this moment that the situation suddenly changed: after 13 years of our Talents being frozen and inert, they suddenly sprang alive and became active, all at once. Some of my fellows became unbound through their various Talents of escape, cutting, or fire, and freed most of us before it was noticed and the chaos of battle truly started.": "我们被绳子绑住，被关在被诅咒的一边。格林达兰人讨论着该如何处置我们：是把我们一个个带过边境，上演一场决斗来安抚他们聚集在一起的战士们的自尊心，还是说这样做风险太大，他们应该把我们都杀了，不用这么戏剧化。就在这一刻，情况突然发生了变化：在我们的天赋被冻结和惰性了13年之后，它们突然活跃起来，变得活跃起来。我的一些同伴通过他们各种各样的逃跑、砍杀或射击的才能挣脱了束缚，在被发现和战斗真正开始混乱之前，他们释放了我们中的大多数人。",
    "Going with the flow of Overclock - for I had neither the will nor the inclination to change its course - it carried me out of combat, out of war, and eventually out of danger entirely. In the few weeks that it guided my path, I continued the repeated miraculous luck even as the effect diminished steadily over time. From finding abandoned horses and supplies, to hearing just the right thing in a conversation, to staying in just the right spot to not be discovered while I slept. Ultimately, [Get Somewhere Safe] had gotten me... Somewhere Safe.": "随着“超频”的流动——因为我既没有意愿也没有意愿改变它的方向——它把我带离了战斗，带离了战争，最终完全脱离了危险。在它指引我前进的那几个星期里，我继续着这种反复出现的奇迹般的运气，即使它的效果随着时间的推移而逐渐减弱。从寻找被遗弃的马匹和物资，到在谈话中听到正确的事情，到待在正确的地方，以免在我睡觉时被发现。最终，《找个安全的地方》让我……安全的地方。",
    "It was eventually named the Ashmarch, for what was left of the land. Gryndall had killed all but a handful of men during the journey itself. Tens of thousands of screams and bodies I marched past, with my vision narrowing on the goal and false hope of crossing the line. We were defenseless, but we marched onward, having come too far for any other choice. Three days it lasted, and the horrors were too great for my mind to hold. The fellow soldiers I saw die, the cries I heard, the traps prepared for us, the unholy desecration of- ... No. Too many horrors. Far too many.": "它最终被命名为阿什马奇，以纪念剩下的土地。格林多在旅途中除了少数几个人之外，几乎杀光了所有人。我走过成千上万的尖叫声和尸体，我的视野缩小了，目标和越过线的虚假希望。我们毫无防备，但我们继续前进，因为我们已经走得太远了，别无选择。这种情况持续了三天，恐怖之情太大，我无法忍受。我看到的战友们死去了，我听到的哭声，为我们准备的陷阱，邪恶的亵渎……否。太多的恐怖。太多了。",
    "Sovvgor's small, long-term ally on our western border, Gryndall, started giving us unfavorable deals. They had been formerly pacified by our might, but realized they had advantages that tipped the scales; they had materials that could be further refined with Talents, and products that were made quicker and with less expertise required, and we had to buy such items at a premium. They had enchanted items and magics that were only made viable through Talents that specialized in them, and we lacked anything to balance the scales. When we ran out of gold to give, their greed only increased and their sights turned to our resources. After a forced diplomatic incident turned into a cry for war, the Emperor had no choice but to prepare an army.": "苏联在我们西部边境的长期小盟友格林德尔，开始给我们不利的交易。他们以前被我们的力量所平定，但是他们意识到他们拥有扭转局势的优势；他们有可以用塔兰特进一步提炼的材料，产品制作速度更快，所需的专业知识也更少，我们不得不花高价购买这些东西。他们拥有只能通过专门的天赋才能使用的附魔物品和魔法，而我们缺乏任何能够平衡天平的东西。当我们没有金子可给的时候，他们的贪婪只会增加，他们的目光转向了我们的资源。在一场被迫的外交事件演变成一场战争之后，皇帝别无选择，只能准备一支军队。",
    "After a few weeks of solitude and focusing on nothing but survival and preparation for winter - blessed stagnancy and repetition - it became obvious that a type of unfamiliar pressure was building: my ability was doing something I had not expected, and it was not simply building passively. I eventually came to realize the pressure became noticeablyy less as I performed tasks that would have been valid targets for Overclock. I was completing my daily chores quicker, but also I was having increasing trouble sitting still after the day's work, and when I had more time I would start to reflect on what got me here - which caused panic and terror and guilt I was desperately trying not to consider. Overclock, when targeting itself, was somehow still making me move, making me think... the momentum was spilling over, somehow. It seemed the choice was still mine for how to relieve the pressure, and so I threw myself into more work.": "几个星期的独处，除了生存和为冬天做准备之外什么都不关注——幸运的停滞和重复——很明显，一种不熟悉的压力正在形成：我的能力正在做一些我意想不到的事情，而且它不是简单地被动地建立起来的。我最终意识到，当我执行那些原本可以成为超频有效目标的任务时，压力明显减轻了。我更快地完成了日常琐事，但也越来越难以在一天的工作结束后坐着不动。当我有更多的时间时，我就会开始反思是什么让我来到这里——这引起了恐慌、恐惧和内疚，我拼命地试图不去考虑。超频，当它瞄准自己时，不知何故仍然让我移动，让我思考……不知何故，这股势头正在蔓延开来。如何减轻压力似乎还是我的选择，所以我投入了更多的工作。",
    "Eventually, I learned the truth of the situation: our mages and enchanters loved magic more than they loved our country, and had moved or been bought out long ago. Worse, some Talents around magic allowed for much greater distance on their magics, or allowed for summons to have a longer leash or greater intelligence, or allowed for the sharing of mana to funnel lesser Talented mages towards the ones who were useful to the situation. Even while still far away from the edge of the curse, we started dying from explosions, clouds of death, and summoned devils that our remaining mages could not adequately defend against.": "最终，我了解了情况的真相：我们的法师和魔法师爱魔法胜过爱我们的国家，他们早就搬走了，或者被收买了。更糟糕的是，一些魔法天赋允许他们的魔法距离更远，或者允许召唤具有更长的约束或更高的智力，或者允许共享法力以将较低天赋的法师输送给对情况有用的法师。即使离诅咒的边缘还很远，我们也开始死于爆炸、死亡之云和召唤出的恶魔，这些都是我们剩下的法师无法抵御的。",
    "I could exist here, and it would be safe - my Talent had guaranteed so. And for a few weeks, I did just that while I settled in. But the nightmares got stronger, and my paranoia was bleeding over into affecting my waking moments, and I started considering how to use the fate-bending exerted by Overclock. In a move to give myself a fallback option, I decided to attempt to replicate the buildup of 13 years. At first I was unsure how to have a \"neutral\" target that could be re-pointed later without needing to find a way to lock it again, but with sudden clarity I tested changing the target... to itself. The target of Overclock became: [Overclock].": "我可以在这里生存，而且这里是安全的——我的天赋保证了这一点。有几个星期，我就是这样安顿下来的。但噩梦越来越强烈，我的妄想症开始影响我醒着的时候，我开始考虑如何利用超频带来的命运扭曲。为了给自己留一个退路，我决定尝试复制13年的积累。一开始我不确定如何拥有一个“中立”的目标，以便在不需要再次锁定它的情况下重新指向它，但我突然清晰地测试了改变目标……本身。超频的目标变成：[超频]。",
    "Later we would learn the curse broke because our Emperor had died from assassination, but at the moment we only had thoughts of survival. When I understood our Talents were active again, and I checked Overclock, something new happened to me: Overclock slammed into me with a metaphysical weight I had never experienced. Over the 13 years it had not been truly inactive, but instead building a reservoir behind a locked gate. It had become far, far more than a \"a little more\". My legs moved on their own, my eyes only tracked my next step, and I ducked and weaved according to whims and currents I had never felt before. Fate herself bent to see my target enacted, and my escape was a circus of coincidences, unforseen Talent ineractions, timing windows, and beginner mistakes from trained veterans that opened a gap large enough for me - and only me - to slip through.": "后来我们才知道诅咒被打破了，因为我们的皇帝死于暗杀，但当时我们只有生存的想法。当我明白我们的天赋再次激活时，我检查了超频，一些新的事情发生在我身上：超频以一种我从未经历过的形而上的重量撞向我。13年来，它并没有真正停止活动，而是在一扇锁着的门后建造了一座水库。它已经远远超过了“多一点”。我的腿可以自己移动，我的眼睛只盯着我的下一步，我根据我以前从未有过的突发奇想和潮流来躲闪躲闪。命运让我的目标成为现实，而我的逃脱是一场由巧合、不可预见的天赋互动、时机窗口和训练有素的老手的初级错误组成的马戏团，这些错误打开了一个足够大的缺口，让我——而且只有我——得以逃脱。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\-([\d\.]+)e([\d\.,]+)$/,
    /^\+([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\-([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\-([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^\-([\d\.]+)M$/,
    /^\+([\d\.]+)M$/,
    /^\-([\d\.]+)B$/,
    /^\+([\d\.]+)B$/,
    /^\-([\d\.]+)T$/,
    /^\+([\d\.]+)T$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Talk With (.+)$/, '与 $1 对话'],
    [/^Consume and send rate is(.+) of fortune \* efficiency.$/, '消耗和发送率为 财富 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of gold \* efficiency.$/, '消耗和发送率为 金币 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of momentum \* efficiency.$/, '消耗和发送率为 动量 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of conversations \* efficiency.$/, '消耗和发送率为 对话 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of fear \* efficiency.$/, '消耗和发送率为 恐惧 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of bravery \* efficiency.$/, '消耗和发送率为 勇敢 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of fight \* efficiency.$/, '消耗和发送率为 战斗 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of mana \* efficiency.$/, '消耗和发送率为 法力 * 效率 的 $1。'],
    [/^Consume and send rate is(.+) of spark \* efficiency.$/, '消耗和发送率为 火花 * 效率 的 $1。'],
    [/^(.+) of (.+) bonus is multiplied to base efficiency$/, '$1 的 $2 加成乘以基础效率'],
    [/^(.+) of (.+) bonus reduces exp to level$/, '$1 的 $2 奖励减少等级经验'],
    [/^(.+) of (.+) bonus reduces progress to complete$/, '$1 的 $2 奖励减少完成进度'],
    [/^Increase (.+) bonus multiplier to (.+) \(Currently: (.+)\)$/, '增加 $1 奖励乘数到 $2（当前: $3）'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\% of Vision bonus reduces progress to complete$/, '$1\% 的 视野 加成降低完成进度'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) AC$/, '$1 转生币'],
    [/^([\d\.,]+) Legacy per complete.$/, '$1 遗物每次完成。'],
    [/^\+(.+) to Curiosity per level.$/, '每级 \+$1 好奇心.'],
    [/^\+(.+) to Coordination per level.$/, '每级 \+$1 协调.'],
    [/^\+(.+) to Amplification per level.$/, '每级 \+$1 放大.'],
    [/^\+(.+) to Wizardry per level.$/, '每级 \+$1 巫术.'],
    [/^\+(.+) to Integration per level.$/, '每级 \+$1 集成.'],
    [/^\+(.+) to Might per level.$/, '每级 \+$1 实力.'],
    [/^\+(.+) to Recognition per level.$/, '每级 \+$1 认可.'],
    [/^\+(.+) to Navigation per level.$/, '每级 \+$1 导航.'],
    [/^\+(.+) to Legacy per level.$/, '每级 \+$1 遗物.'],
    [/^\+(.+) to Flow per level.$/, '每级 \+$1 流动.'],
    [/^\+(.+) to Cunning per level.$/, '每级 \+$1 狡猾.'],
    [/^\+(.+) to Charm per level.$/, '每级 \+$1 魅力.'],
    [/^\+(.+) to Savvy per level.$/, '每级 \+$1 悟性.'],
    [/^\+(.+) to Vision per level.$/, '每级 \+$1 视野.'],
    [/^\+(.+) to Awareness per level.$/, '每级 \+$1 意识.'],
    [/^\+(.+) to Energy per level.$/, '每级 \+$1 能量.'],
    [/^\+(.+) to Observation per level.$/, '每级 \+$1 观察.'],
    [/^\+(.+) to (.+) per level.$/, '每级 \+$1 $2.'],
    [/^Brythal \[([\d\.,]+)\]$/, '布里塔尔 [$1]'],
    [/^Tier ([\d\.,]+) Action$/, '层级 $1 动作'],
    [/^Tier ([\d\.,]+) Generator$/, '层级 $1 生成器'],
    [/^Stage ([\d\.,]+)$/, '关卡 $1'],
    [/^All ([\d\.,]+)$/, '全部 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);