/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Use Bonus Code": "使用奖励代码",
    "Your world ended, and they only live on through you. Think about what they would\n    have wanted for you, and on how much you miss them, and let it drive you forward. This is an internal story as much\n    as it is an external one.": "你的世界结束了，他们只能通过你活下去。想想他们会对你有什么期望，想想你有多想念他们，让思念驱动你前进。这是一个内部和外部的故事。",
    "You Need A Break": "你需要休息一下",
    "Worry": "担心",
    "/complete)": "/完成)",
    "/lvl": "/等级",
    "/s)": "/秒)",
    "/s": "/秒",
    "Confirm": "确认",
    "Control": "控制",
    "Controls to Move Around": "移动控制",
    "Conversations": "对话",
    "cost:": "成本:",
    "Data": "数据",
    "Attributes": "属性",
    "Deep Investments": "深度投资",
    "Attributes >>": "属性 >>",
    "Aura Control": "光环控制",
    "Aura Healing": "光环愈合",
    "Auto save every 20 seconds and on pause, but if you want a button to click:": "每隔20秒自动保存并暂停，但如果你想点击按钮：",
    "Awaken Your Grimoire": "唤醒你的魔法书",
    "Background": "背景色",
    "Basic Training With John": "约翰的基础训练",
    "Bind The Pages": "绑定页面",
    "Body Awareness": "身体意识",
    "Bonus Time:": "加成时间:",
    "Bonus Speed:": "加成速度:",
    "bonus mult": "加成乘数",
    "Bridge Of Bone": "骨桥",
    "Browse Stores": "浏览商店",
    "Burn Flesh Pits": "烧肉坑",
    "Buy": "购买",
    "Buy Coffee": "购买咖啡",
    "Buy Social Access": "购买社交访问",
    "Buy Shop Items": "购买商店物品",
    "Buy Good Food": "购买美食",
    "Buy Street Food": "购买路边食物",
    "Buy Basic Clothes": "购买基础衣服",
    "Buy Matching Clothes": "购买搭配衣服",
    "Buy Stylish Clothes": "购买时尚衣服",
    "Buy Travelers Clothes": "购买旅行者衣服",
    "Buy Basic Supplies": "购买基础物资",
    "Buy Bonus Time:": "购买加成时间:",
    "Changing Colors": "更改颜色",
    "Change": "更改",
    "Charges": "充能",
    "Charm": "魅力",
    "Chat With Hermit": "与隐士交谈",
    "Chat With Merchants": "与商人交谈",
    "Clock:": "时钟:",
    "CLOSED BETA": "封闭测试",
    "Command": "Command",
    "View Amulet Upgrades!": "查看护身符升级！",
    "Vision": "视野",
    "WAIT": "等待",
    "Walk Aware": "行走意识",
    "Ward": "结界",
    "Ward Magic": "结界魔法",
    "Unlocks 5 new actions.": "解锁5个新动作",
    "Use the Amulet!": "使用护身符！",
    "Valor": "英勇",
    "Wizardry": "巫术",
    "Work in Progress. The shop will be completed for full release with the following plans. \n        I will keep the game ad-free and AI-art free, and the demo will be open-source on my github.": "工作进行中。商店将完成全面发布与以下计划。我将保持游戏不含广告和ai图像，demo将在我的github上开源。",
    "You can fully delete the numbers in sliders now": "您现在可以完全删除滑块中的数字",
    "You pay respect to the shrine, \n        and feel your amulet resonate with feelings around this shrine.": "你对神殿表示敬意，并感到你的护身符与神殿周围的情感产生共鸣。",
    "You will gain progress using Total Momentum, Hear About The Lich's level, and Spell Power!": "你将通过使用总动量，听说巫妖的等级和法术力量获得进步！",
    "You'll help me, for real? Wow, I didn't know you were cool like that.": "You'll help me, for real? Wow, I didn't know you were cool like that. ",
    "You'll help? Oh, you": "你会帮忙吗？哦，你",
    "Your motivation to overclock spills over throughout your mind. Your general drive expands, and you put this to use in making money. At first it's whatever odd jobs you can find, with later getting employed, Making Money is the gateway to improving your situation.": "你想要超频的动机充斥着你的大脑。你的整体动力得到了扩展，你把它用于赚钱。一开始是你能找到的任何奇怪的工作，随着之后的工作，赚钱是改善你的状况的途径。",
    "Mana": "法力",
    "mana": "法力",
    "Mana Basics": "法力基础",
    "Mana Experiments": "法力实验",
    "Mana Instinct": "法力本能",
    "Mana Observations": "法力观察",
    "Mana Shaping": "法力塑造",
    "Mana Transfer": "法力转移",
    "Mana Visualizations": "法力可视化",
    "Mana, added to this action.": "法力，添加到此动作。",
    "Mass Heal": "群体治疗",
    "MAX CHARGES": "充能上限",
    "Max Level": "最大等级",
    "MAX LEVEL": "最大等级",
    "Meditate": "冥想",
    "Meet Grumpy Hermit": "Meet Grumpy Hermit",
    "Meet People": "结识新朋友",
    "Menu": "菜单",
    "Might": "实力",
    "Modified text of on-level attributes": "修改了等级属性的文本",
    "Messenger": "信使",
    "On Complete:": "完成:",
    "Offline >>": "离线 >>",
    "Offline time constantly saves instead of only when the page unloads": "离线时间会不断地节省下来，而不仅仅是在页面卸载时",
    "NOTICE - Market Ads": "公告 - 市场广告",
    "NOTICE - A hidden notice": "公告 - 一个隐藏的通知",
    "NOTICE - Report for Training": "公告 - 培训报告",
    "Notice The Strain": "注意张力",
    "Number Notation": "数字符号",
    "Odd Jobs Laborer": "临时工",
    "Off": "关闭",
    "On": "开启",
    "Detect Magic": "侦测魔法",
    "Destroy Western Monolith": "摧毁西方巨石",
    "Destroy Southern Monolith": "摧毁南方巨石",
    "Destroy Northern Monolith": "摧毁北方巨石",
    "Destroy Eastern Monolith": "摧毁东方巨石",
    "Destroy Flesh Growths": "摧毁肉体生长",
    "Deception": "欺骗",
    "Delta Unlock Time:": "德尔塔解锁时间:",
    "Cycle": "周期",
    "Current Job:": "当前工作:",
    "Current Unlock Time:": "当前解锁时间:",
    "...Ask Scott More Questions": "...斯科特更多问题",
    "...Buy Nicer Stuff": "...买更好的东西",
    "legacy": "遗产",
    "Legacy": "遗产",
    "Level": "等级",
    "Let Go Of Guilt": "放下内疚",
    "Logarithmic": "对数",
    "Listen To The Mana": "聆听法力",
    "Listen To Woes": "聆听悲伤",
    "Logistics": "物流",
    "Magic": "魔法",
    "Research": "研究",
    "Make Money": "赚钱",
    "Making Money": "赚钱",
    "Momentum": "动量",
    "momentum": "动量",
    "Meet Village Leader Scott": "会见村长斯科特",
    "Money": "金钱",
    "Move Earth": "动天地",
    "Move With Purpose": "有目的的行动",
    "Needs": "需要",
    "Navigation": "导航",
    "Observation": "观察",
    "On Level up:": "当升级:",
    "Welcome to Kill the Lich! Click Here for Info!": "欢迎来到《杀死巫妖》！点击这里获取信息！",
    "Exp and Leveling": "经验与等级",
    "Watch Birds": "观鸟",
    "progress\n                (+": "进度\n                (+",
    "Processing": "处理中",
    "Process Emotions": "处理情绪",
    "Previous Unlock Time:": "前一次解锁时间:",
    "Previously Closed Tips": "以前关闭的提示",
    "Previous Tips": "之前的提示",
    "Purify Poison": "净化毒药",
    "Raising Max Levels": "提高最大等级",
    "Put your save here to import (import a clear save to hard reset):": "把你的存档放在这里导入（导入一个清晰的存档来硬重置）：",
    "|| Pause": "|| 暂停",
    "Spend Money": "花钱",
    "Start Again": "重新开始",
    "Starting the Game": "开始游戏",
    "Stat Modifiers to Efficiency:": "效率的属性修饰：",
    "Stats": "属性",
    "Stop Darkness Ritual": "停止黑暗仪式",
    "Stop_Sign Gaming": "停止签游戏",
    "Story": "故事",
    "Story Teller": "说书人",
    "Suffix": "后缀",
    "Toast Title": "祝酒称号",
    "Total Momentum,": "总动量，",
    "Total Momentum:": "总动量:",
    "exp\n                (+": "经验值\n                (+",
    "Energy": "能量",
    "Endurance": "耐力",
    "Enter Bonus Code:": "输入奖励代码：",
    "Etch The Circle": "蚀刻圆圈",
    "Downstream": "",
    "Browse Local Market": "浏览本地市场",
    "Browse Personal Collection": "浏览个人收藏",
    "Browse Backrooms": "浏览密室",
    "Breathe Through It": "透过它呼吸",
    "Overclock": "超频",
    "Overdrive": "超速",
    "Own The Weight": "拥有重量",
    "per level": "每级",
    "Physique": "体格",
    "Pleasant Forest": "宜人森林",
    "Pool Mana": "池法力",
    "Prepare Spells": "准备法术",
    "Pulse": "脉冲",
    "Purge Unholy Relics": "清除不洁圣物",
    "Read Books": "读书",
    "Reflect": "反射",
    "Recognition": "认可",
    "sent from": "发送来自",
    "Shop": "商店",
    "Show +/-/Δ Values": "显示 +/-/Δ 值",
    "Slide The Coin": "滑动硬币",
    "Socialization": "社会化",
    "Sort By Subject": "按主题分类",
    "Spell": "法术",
    "Spell Power:": "法术力量:",
    "Spot A Path": "找到一条路",
    "Stand Straighter": "站得更直",
    "Tell A Joke": "讲个笑话",
    "Buy Market Items": "购买市场物品",
    "Build Fortune": "创造财富",
    "Catalog New Books": "编目新书",
    "Catch A Scent": "捕捉气味",
    "Changing your overclock target will set you on a new path to get as much Ancient Coins and Legacy as you can.": "改变你的超频目标将使你走上一条新的道路，以获得尽可能多的古币和遗物。",
    "Check Notice Board": "检查公告栏",
    "Bonus = 10% per Stat.": "奖励 = 10% 每属性.",
    "Integration": "集成",
    "Inquire About Magic": "询问魔法",
    "Increase": "增加",
    "Influence": "影响",
    "Infuse The Hide": "浸皮",
    "Invest In Roads": "投资道路",
    "Invest In Locals": "投资本地",
    "Introspection": "自省",
    "Spellcraft": "法术制作",
    "Stat Modifiers to Exp:": "经验的属性修饰：",
    "Stillness": "静止",
    "Support Spells": "支持法术",
    "Survive Living Siege Engine": "求生攻城引擎",
    "Enable Bonus Speed": "启用奖励速度",
    "Overboost": "超增压",
    "Overcharge": "过度充能",
    "Tavern Helper": "酒馆助手",
    "Thanks for playing!": "谢谢你的参与！",
    "Take Notes": "做笔记",
    "Swarm Spells": "群体法术",
    "Stats gained each level:": "每级属性增益：",
    "How to Provide Feedback": "如何提供反馈",
    "Hear About The Lich": "听说巫妖的事",
    "Heal Burst": "治愈爆发",
    "Healing Magic": "治愈魔法",
    "Help For Real": "真正的帮助",
    "Help Scott With Chores": "帮斯科特做家务",
    "Here is a message": "这里有一条消息",
    "gold": "金币",
    "Gold": "金币",
    "Gold generation increased by 50%": "金币产量增加50%",
    "gold, added to Spend Money.": "金币，增加到花钱。",
    "Harness Overflow": "利用溢出",
    "Handyman": "杂工",
    "Harvest Ghostly Field": "收获幽灵田",
    "Geyser Fields": "间歇泉田",
    "Gather Rare Plants": "收集稀有植物",
    "Gather Old Books": "收集旧书",
    "Gather River Weeds": "收集河道杂草",
    "Join the War for Life with": "加入生命之战",
    "Kill The Architect": "杀死建筑师",
    "Journal": "日记",
    "Distill Insight": "蒸馏洞察力",
    "Join Coffee Club": "加入咖啡俱乐部",
    "Learn To Listen": "学会倾听",
    "Kill Dopplegangers": "击杀分身",
    "Key To The Backroom": "密室的钥匙",
    "Kill Death Knights": "击杀死亡骑士",
    "Keep 50% (Currently 10%) of your Legacy when you use the Amulet": "当你使用护身符时，保留50%（现在是10%）的遗物",
    "Layer The Echoes": "分层回声",
    "Leave The Open Road": "Leave The Open Road",
    "Learn To Stay Still": "学会保持静止",
    "Leverage": "杠杆作用",
    "Linear": "线性",
    "Momentum was added.": "动量增加了。",
    "Fight": "战斗",
    "fight": "战斗",
    "Fight The Evil Forces": "对抗邪恶势力",
    "Fight The Lich": "对抗巫妖",
    "Fight, added to Fight The Evil Forces.": "战斗，添加对抗邪恶力量。",
    "Find Overlook": "发现远眺",
    "Game Math on Sending": "发送的游戏数学",
    "Finding New Actions": "寻找新动作",
    "Help": "帮助",
    "Hesitation": "犹豫",
    "Hidden Path": "隐藏路径",
    "Honor The Lost": "纪念逝者",
    "Highest level (2x up to):": "最高级别（最高可达2x）：",
    "Guild Receptionist": "公会接待员",
    "Grow Magic Senses": "培养魔法感官",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Magic ": "魔法 ",
    "Total Reduction = ": "总减少量 = ",
    "% efficiency": "% 效率",
    "% instability": "% 不稳定性",
    "Kill The Lich": "杀死巫妖",
    "Kill the Lich": "杀死巫妖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Soul Coins": "灵魂币",
    "Soul Coins (SC)": "灵魂币 (SC)",
    "As I observed the various actions that I had thus felt out, I realized that Reflect and Distill Insight had some whirls \nI could smooth out by controlling their spins into joining the river quicker.": "当我观察到各种各样的动作时，我意识到“反射”和“提炼洞察力”有一些旋涡，我可以通过控制它们的旋涡来更快地加入河流。",
    "Overclock was a storm, and difficult for me to fully access. I didn't quite understand, but feeling out those complicated ever-changing knots,\n it also sparked the tip of a memory. I had been confused - why was this familiar?\n": "超频是一场风暴，对我来说很难完全访问。我不太明白，但摸出那些复杂多变的结，也勾起了记忆的一角。我一直很困惑——为什么这很熟悉？\n",
    "Going with the flow of my ability, it carried me out of the fire, out of the war, out of danger, out of caution, and \n    into Safety. Over the next few weeks, I continued the repeated miraculous luck, though the effect diminished over time.\n    From finding abandoned horses and supplies, to hearing just the right thing in a conversation, to staying in just the \n    right spot to not be discovered while I slept. Ultimately, [Get Somewhere Safe] had gotten me... Somewhere Safe.": "随着我的能力的流动，它带我离开了火灾，离开了战争，离开了危险，离开了谨慎，进入了安全。在接下来的几个星期里，我继续重复着这种神奇的运气，尽管这种效果随着时间的推移而减弱。从寻找被遗弃的马匹和物资，到在谈话中听到正确的事情，到呆在正确的地方，在我睡觉的时候不被发现。最终，[去安全的地方]让我……安全的地方。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\-([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Talk With (.+)$/, '与 $1 交谈'],
    [/^(.+) of (.+) bonus is multiplied to base efficiency$/, '$1 的 $2 加成乘以基础效率'],
    [/^(.+) of (.+) bonus reduces exp to level$/, '$1 的 $2 奖励减少等级经验'],
    [/^(.+) of (.+) bonus reduces progress to complete$/, '$1 的 $2 奖励减少完成进度'],
    [/^Increase (.+) bonus multiplier to (.+) \(Currently: (.+)\)$/, '增加 $1 奖励乘数到 $2（当前: $3）'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\% of Vision bonus reduces progress to complete$/, '$1\% 的 视野 加成降低完成进度'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) AC$/, '$1 转生币'],
    [/^\+([\d\.,]+) to Curiosity per level.$/, '每级 \+$1 好奇心.'],
    [/^\+([\d\.,]+) to Coordination per level.$/, '每级 \+$1 协调.'],
    [/^\+([\d\.,]+) to Amplification per level.$/, '每级 \+$1 放大.'],
    [/^\+([\d\.,]+) to Wizardry per level.$/, '每级 \+$1 巫术.'],
    [/^\+([\d\.,]+) to Integration per level.$/, '每级 \+$1 集成.'],
    [/^\+([\d\.,]+) to Might per level.$/, '每级 \+$1 实力.'],
    [/^\+([\d\.,]+) to Recognition per level.$/, '每级 \+$1 认可.'],
    [/^\+([\d\.,]+) to Navigation per level.$/, '每级 \+$1 导航.'],
    [/^\+([\d\.,]+) to Legacy per level.$/, '每级 \+$1 遗物.'],
    [/^\+([\d\.,]+) to Flow per level.$/, '每级 \+$1 流动.'],
    [/^\+([\d\.,]+) to Cunning per level.$/, '每级 \+$1 狡猾.'],
    [/^\+([\d\.,]+) to Charm per level.$/, '每级 \+$1 魅力.'],
    [/^\+([\d\.,]+) to Savvy per level.$/, '每级 \+$1 悟性.'],
    [/^\+([\d\.,]+) to Vision per level.$/, '每级 \+$1 视野.'],
    [/^\+([\d\.,]+) to Awareness per level.$/, '每级 \+$1 意识.'],
    [/^\+([\d\.,]+) to Energy per level.$/, '每级 \+$1 能量.'],
    [/^\+([\d\.,]+) to Observation per level.$/, '每级 \+$1 观察.'],
    [/^\+([\d\.,]+) to (.+) per level.$/, '每级 \+$1 $2.'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);